### ISSUE TITLE
TuGraph Browser  import data failed

### ISSUE THREAD

**Issue by Reid00** [TuGraph-family/tugraph-db#100]
does the browser has data size limit? when I sample little data it works good while whole file failed as image
![image](https://user-images.githubusercontent.com/38450639/200555233-aa183e8e-b983-4244-945c-d363211610e8.png)

**Comment by KingSkyLi** [comment]
Currently, an error occurs when the file size exceeds 2 GB. You are advised not to import large data on the visual interface.

**Comment by Reid00** [comment]
Got it, maybe this info should be written in docs.
