### ISSUE TITLE
请问能给边的属性创建索引吗？我看文档说只支持给点的属性创建索引

### ISSUE THREAD

**Issue by GoGoMonkey123** [TuGraph-family/tugraph-db#123]
如果边上的属性不支持创建索引的话，那是不是意味着不推荐通过边的属性来进行相关查询？

**Comment by knightast** [comment]
边上支持索引，在procedure api里有，你也可以看看UT。

一般图模型是先查点，再查该点对应的边。

**Comment by qishipengqsp** [comment]
此Issue已保持7个月不活跃状态，先关闭，如有问题可以再次开启。
