### ISSUE TITLE
Docker Images 版本更新

### ISSUE THREAD

**Issue by idb-root** [TuGraph-family/tugraph-db#127]
请问可以尽快更新Docker Images 版本为3.3.2吗？多谢

**Comment by KingSkyLi** [comment]
您好3.3.2版本已经发布了。你可执行docker pull tugraph/tugraph-runtime-centos7:3.3.2进行拉取。
具体版本可见：https://hub.docker.com/r/tugraph/tugraph-runtime-centos7/tags
