### ISSUE TITLE
data目录落盘

### ISSUE THREAD

**Issue by idb-root** [TuGraph-family/tugraph-db#128]
挂载原来的数据库到/var/lib/lgraph目录下，启动报错如下，请问是什么原因？
ParseJson skipping enable_ha : false
ParseJson skipping license : /var/lib/lgraph/fma.lic
Listening for RPC on port 9090
Server hit an exception and shuts down abnormally:
KvException: Failed to apply logs, unexpected TXN_BEGIN
Server shutdown.

**Comment by GreenAppleOne** [comment]
这个问题有解决计划吗?升级之后 之前的数据没办法加载了

**Comment by KingSkyLi** [comment]
这个问题会在后面的迭代中完成优化。

**Comment by qishipengqsp** [comment]
可以看看这个有没有帮助
https://tugraph-db.readthedocs.io/zh-cn/latest/7.best-practices/3.data_migration.html?highlight=%E8%BF%81%E7%A7%BB#id3

**Comment by qishipengqsp** [comment]
The issue is closed due to inactivity. Please feel free to create a new one if you have more questions. And please star this repo if you find it useful! Thanks!
此issue由于长期不活跃被关闭。如有任何问题，可另开 issue 并提供更多信息。如果这个项目帮助到你，可以在仓库右上角 star 一下，感谢你的支持!
