### ISSUE TITLE
怎样挂载数据盘？

### ISSUE THREAD

**Issue by idb-root** [TuGraph-family/tugraph-db#130]
/var/lib/lgraph/data/.meta
把.meta目录删除后，挂载到新版本的容器下，正常启动。
但，登录web后台，并没有原来的数据。还是一个全新的后台。

请问以上方式挂载是不是不行？怎样把原来的data目录挂载到全新的容器上？

**Comment by knightast** [comment]
.meta数据不能删，里边有用户、多图的一些数据，把整个db拷出来试试。正规的用法是先lgraph_backup，再lgraph_restore

**Comment by qishipengqsp** [comment]
此Issue已保持7个月不活跃状态，先关闭，如有问题可以再次开启。
