### ISSUE TITLE
Docker版本：关于导入模型时内存过小以及意外关闭docker导致数据库损坏等2个问题的说明

### ISSUE THREAD

**Issue by rubbishgod** [TuGraph-family/tugraph-db#131]
在Win7上试用Docker（3.3.2）时，发现2个问题：
1、使用 /demo/movide/run_import.sh，以离线方式导入自定义的CSV数据时，若虚拟机内存较小（如2G），而待导入文件较大（如1G），则能够显示"IMPORT DONE."，且导入后的数据目录"/var/lib/lgraph/movie_db"中也有较大的文件存在。但启动数据库服务（run_server.sh）后，通过 http://localhost:7070 无法查询出结果（我尝试了很多次，大多情况下能成功导入并查看到schema，但都无法查询出数据库记录）。若将自定义CSV数据行数减少（如减少至100），或者将虚拟机内存设置更大一些（如32GB），则一切正常。
个人见解：总体而言，导入速度非常快，但上述问题意味着，导入模型时，必须保证设备内存足够大。所以请问是否有大致的对应关系，或者说是否可优化lgraph_import程序，令其报错更人性化，或者解决内存相对较小条件下的数据导入问题。
2、当数据库出现长时间无查询结果时，我将docker container停止再启动（也试过用lgraph_server -d stop停止再启动），此时极其容易出现数据库无法正常运行的情况，等于说之前存储的所有数据都无法访问了。请问这种情况是否有补救措施，或者说是否有相关的工具可以进行修复？

**Comment by knightast** [comment]
1. 可能是db文件不完整，不能读出正确的数据。这个不应该，如果写失败会报错。目前lgraph_import会在内存维护点的primary key到vid的map，做了个类似外排的事，数据不均匀边的block读入可能也会占比较多的内存。这个问题有挺多人反应了，正在解决中，重构下import逻辑。
2. 这个也非常奇怪，你把db文件整个拷出来应该直接能换个环境使用，试试在linux有没类似的问题。

**Comment by KingSkyLi** [comment]
和开发同学讨论，目前docker容器在window的wsl的linux子系统上，会出现偶发的容器启动失败的问题。目前建议可以使用CentOs或Ubuntu系统进行docker容器或直接部署使用。您也可以将本地报错信息截图反馈给我们，我们也会持续优化docker容器服务。

**Comment by rubbishgod** [comment]
谢谢回复。
关于1：我现在换了台WinServer2012R2服务器在测试，虚拟机内存设置为120GB，虚拟机硬盘设置的2T，暂时没问题了。。。关于Linux系统，在初步试用后一定会考虑的。对了，Win10之前的系统用的是DockerToolbox（虚拟机用的是VirtualBox），Win10用的是DockerForWindows（基于WSL）
现在我遇到一个新问题，那就是：离线导入速度还可以接受，我导入1000万个person节点（只有id和name，2个都有索引）、10亿条边，好像用了不超过15分钟；但是，再通过在线方式导入1000万点、10亿边，用了应该超过8个小时了，好像才导入百分之20不到，目前还没有报错。。。我原计划导入上亿个节点、上百亿边。。。感觉基本不可能了。。。所以**请问导入数亿节点、上百亿边的数据，是不是已经不适合单机？如果分布式部署的话，导入速度大概如何？**
关于2：最近试用较少，但目前我已经习惯了统计边、节点数时的慢了，哈哈，不会主动去终止它了，因为查询时间一般不超过15分钟，忙会儿别的再回过来看就行了。我记得在运行“lgraph_server -c lgraph.json”时就报错。下次出错时，我记得截个图发上来。

**Comment by knightast** [comment]
1. 你算一下导入速度，离线大概是50MB/s，在线大概5MB/s，确实差一个数量级。主要每条数据都会检查一致性，更新vid。存量数据导入还是建议离线导入，后面在线的增量数据看5MB/s够不够用。
2. 后面报个bug，尽量提到discussion里。

**Comment by KingSkyLi** [comment]
目前离线导入和在线导入的速度确实会有较大差距，主要是因为在线导入需要校验节点ID来保证数据的一致性。
启动服务报错，可以截图看下报错原因

**Comment by qishipengqsp** [comment]
此Issue已保持7个月不活跃状态，先关闭，如有问题可以再次开启。
