### ISSUE TITLE
用户登录 jwt过期时间是多少，请求jwt登陆频率有没有限制

### ISSUE THREAD

**Issue by songlf1002** [TuGraph-family/tugraph-db#141]
![image](https://user-images.githubusercontent.com/70573089/210546910-964bc573-15f0-4935-b3d5-7124e95ebac9.png)

**Comment by lloydzhou** [comment]
jwt应该是会自己包含过期时间之类的信息。

[src/db/token_manager.h](https://github.com/TuGraph-db/tugraph-db/tree/master/src/db/token_manager.h)文件有定义过期时间

```
#define TOKEN_REFRESH_TIME 3600
#define TOKEN_EXPIRE_TIME 3600 * 24
```

刚刚看了看python client的代码，应该是没有刷新token的逻辑，估计得自己做，或者自己提pr加上对应的逻辑吧

**Comment by KingSkyLi** [comment]
在3.3.3版本会优化JWT相关逻辑，同时也会有相关的过期时间和刷新token的接口。

**Comment by qishipengqsp** [comment]
JWT逻辑已优化，可以再看一下。

**Comment by qishipengqsp** [comment]
The issue is closed due to inactivity. Please feel free to create a new one if you have more questions. And please star this repo if you find it useful! Thanks!
此issue由于长期不活跃被关闭。如有任何问题，可另开 issue 并提供更多信息。如果这个项目帮助到你，可以在仓库右上角 star 一下，感谢你的支持!
