### ISSUE TITLE
编译demo/CppRpcClientDemo后没有python_client.so，无法运行python客户端

### ISSUE THREAD

**Issue by GGL12** [TuGraph-family/tugraph-db#147]
运行 python客户端：python3 client_python.py -i 127.0.0.1 -p 9090 -u admin --password 73@TuGraph -g default -c "MATCH (n) RETURN n LIMIT 100" ，无法找到python_client包

**Comment by spasserby** [comment]
需要python_client.so，这个在build/output目录下面(make或者make python_client生成)
如果是已经直接使用docker image，那么在/usr/local/lib64下面

**Comment by spasserby** [comment]
1）python_client.so和demo/CppRpcClientDemo没有关系
2）3.3.2镜像遗漏了python_client.so，问题会尽快修复（预计3.3.4，目前3.3.3有相同的问题
3）解决方法一：手动生成python_client.so，需要单独编译TuGraph，方法参考：
https://github.com/TuGraph-db/tugraph-db#2-build-from-source
4）解决方法二：使用TuGraphClient.py：
https://github.com/TuGraph-db/tugraph-db/tree/master/src/client/python/TuGraphClient

**Comment by qishipengqsp** [comment]
此Issue已保持6个月不活跃状态，先关闭，如有问题可以再次开启。
