### ISSUE TITLE
找不到import lgraph.Lgraph;

### ISSUE THREAD

**Issue by 30485605** [TuGraph-family/tugraph-db#151]
lgraph.Lgraph 找不到这个类，请问这个类源码在哪

**Comment by KingSkyLi** [comment]
是使用Python的client吗？

**Comment by 30485605** [comment]
用的是java client
![image](https://user-images.githubusercontent.com/28747971/212834464-38b570bb-428c-4f2d-bdd9-baa5bb7a99c5.png)

**Comment by qishipengqsp** [comment]
这个类是proto编译出来的

**Comment by qishipengqsp** [comment]
The issue is closed due to inactivity. Please feel free to create a new one if you have more questions. And please star this repo if you find it useful! Thanks!
此issue由于长期不活跃被关闭。如有任何问题，可另开 issue 并提供更多信息。如果这个项目帮助到你，可以在仓库右上角 star 一下，感谢你的支持!
