### ISSUE TITLE
运行call_plugin例子提示"Plugin [_fma_khop] does not exist."

### ISSUE THREAD

**Issue by wzg-zhuo** [TuGraph-family/tugraph-db#159]
**Describe the bug**
client = TuGraphClient(ip:port , "admin", "73@TuGraph")
plugin_type = "cpp"
plugin_name = "khop"
plugin_input = "{\"root\": 0, "\hop\": 3}"
ares = client.call_plugin(plugin_type, plugin_name, plugin_input)
print(ares)
提示错误
OSError: Failed to get response from server after retrying: Error returned from server, code=[400], msg=[Plugin [_fma_khop] does not exist.]

**Comment by KingSkyLi** [comment]
`client.call_plugin` is to execute `plugin`. Before execution, you need to load the plugin into TuGraph. You can use the `plugin` module of the visualization tool to check whether the loading is successful.

**Comment by wzg-zhuo** [comment]
> 

请问如何load plugin,是否有例子可以参考

**Comment by qishipengqsp** [comment]
Duplicated to #347. Will fix. Please follow up there.
