### ISSUE TITLE
Boolean operators work without space after a string

### ISSUE THREAD

**Issue by CAQ** [TuGraph-family/tugraph-db#162]
**Is your feature request related to a problem? Please describe.**
``MATCH p=(m)-[]->(n:genre) WHERE n.name='Action' AND m.duration>160 RETURN p`` works, but
``MATCH p=(m)-[]->(n:genre) WHERE n.name='Action'AND m.duration>160 RETURN p`` not (ParserException).

**Describe the solution you'd like**
I'd suggest both of them work.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by spasserby** [comment]
Currently, spaces are required around the "AND".
You can try modifying the "oC_AndExpression" in Lcypher.g4.
oC_AndExpression : oC_NotExpression  ( (SP)* AND (SP)* oC_NotExpression )* ;

**Comment by qishipengqsp** [comment]
The issue is closed due to inactivity. Please feel free to create a new one if you have more questions. And please star this repo if you find it useful! Thanks!

此issue由于长期不活跃被关闭。如有任何问题，可另开 issue 并提供更多信息。如果这个项目帮助到你，可以在仓库右上角 star 一下，感谢你的支持!
