### ISSUE TITLE
Node property settings missing when exporting the schema

### ISSUE THREAD

**Issue by CAQ** [TuGraph-family/tugraph-db#165]
When exporting the schema from the web interface, the exported JSON file doesn't describe the following settings of node properties: Optional, Indexed, and Unique. As a result, when importing the schema from this JSON file, these settings are set to default values (false, false, false, or primary key: false, true, true).
Expected behavior: These settings are described in the JSON file.

**Comment by knightast** [comment]
It will be fixed in version 3.4.0, which will be released in one or two weeks.

**Comment by qishipengqsp** [comment]
Already fixed
