### ISSUE TITLE
[Doc] The user rights management doc is out of data

### ISSUE THREAD

**Issue by frank-zsy** [TuGraph-family/tugraph-db#177]
**Describe the bug**

In production env, we really need a user access management for our databases.

But in the [`User rights management` doc](https://www.tugraph.org/doc?version=V3.3.2&id=10000000000842603), the functions are out of date right now and can not be used to setup user access rights correctly like:

- `modSpecifiedAccessLevel` function does not exist anymore, the name of the function should be `modRoleAccessLevel` now, so there will be an error about `unregistered standalone function` if we call `modSpecifiedAccessLevel` in the Cypher.

I think we should keep the document identical with the code at our best to make sure users can setup the database properly by themselves.

**Comment by frank-zsy** [comment]
Also, we should give some examples about how to use the functions since users may not understand how to properly set a `Map` param to functions like `CALL dbms.security.modSpecifiedAccessLevel(role::STRING,access_level::MAP)`.

**Comment by knightast** [comment]
A lot of efforts should be made to enhance doc, thanks for detailed suggestion.

Currently, all interface are tested in UT, you can also find the examples in UT (which should be put in doc).

**Comment by frank-zsy** [comment]
I think I can help with the update of this doc and sync the function from UT to doc.
