### ISSUE TITLE
[Feature] Check exists functions for procedures

### ISSUE THREAD

**Issue by frank-zsy** [TuGraph-family/tugraph-db#183]
**Is your feature request related to a problem? Please describe.**

Right now, in cpp/python procedures, we can only use `db.GetVertexByUniqueIndex(label, "id", 123)` to perform an equivalent query as `MATCH (n:label{id:123}) RETURN n`. But this function will raise an exception if the vertex does not exist.

And the same thing for edges.

**Describe the solution you'd like**

As check and create or update is quite common for graph data import process, and try/catch will introduce much more runtime cost to the code even if there is no exception. So we really need functions to check vertex/edges existence without exception but only return true/false to indicate if the entity exists.

**Describe alternatives you've considered**

Right now, try/catch can be used but not quite friendly or efficient.

**Comment by knightast** [comment]
TuGraph have a lot exception in C++ Procedure API, and also has "IsValid" to check if there may throw. Performance is already considered to avoid exception in inner loop. Cypher has no exception.

If no exception allowed, there always should be a return value to check if success, and it's also not elegant. Do you have further API suggestion?

**Comment by frank-zsy** [comment]
But right now, if I use `vi = db.GetVertexByUniqueIndex(label, "id", 123)` and there is no vertex to return, I can not `vi.IsValid()` to check the result since the exception is already thrown. I checked C++ and Python cost of try/catch and they say try/catch without exception does not make more costs, so I think throw exceptions is just fine.
