### ISSUE TITLE
导出图片报错

### ISSUE THREAD

**Issue by natureLanguageQing** [TuGraph-family/tugraph-db#184]
**Describe the bug**
在火狐浏览器中无法进行截图

**To Reproduce**
1. 基于docker 安装tugraph 
2. 导入实体关系数据
3. 运行查询语句
4. 点击导出

**Expected behavior**
导出无响应
控制台报错

**Screenshots**
![1679970677169](https://user-images.githubusercontent.com/37429336/228111988-e32dcf79-f629-4045-83f9-fe648ab63484.png)

**Environment:**
 - windows: 11
 - docker wsl

**Comment by knightast** [comment]
您这边是哪个版本？可以在控制台看到。以及怎么部署的？

可以简单验证下Chrome的操作正常么？

**Comment by qishipengqsp** [comment]
此Issue已保持4个月不活跃状态，先关闭，如有问题可以再次开启
