### ISSUE TITLE
使用lgraph_import工具，显示成功，但数据未导入

### ISSUE THREAD

**Issue by 19wyy** [TuGraph-family/tugraph-db#186]
**报错原因：**
使用lgraph_import工具，显示成功，但数据未导入
**错误描述**
下图中已经显示成功，但是在web界面中未看到数据
![image](https://user-images.githubusercontent.com/86821930/228521149-40cf8724-dd53-4268-b34f-a9abd7b793ba.png)

**Comment by 19wyy** [comment]
![image](https://user-images.githubusercontent.com/86821930/228521599-c4b150c0-c821-44d8-8875-f7e1c0f3bedd.png)

**Comment by cptrailblazer** [comment]
你好，请问如何安装lgraph_import？我在官方文档里没有找到

**Comment by 19wyy** [comment]
> 你好，请问如何安装lgraph_import？我在官方文档里没有找到

我的是在这个目录，希望对你有帮助
![image](https://user-images.githubusercontent.com/86821930/228740617-97cd0445-b873-42e1-9c9c-e566ba2ca49d.png)

**Comment by cptrailblazer** [comment]
> > 你好，请问如何安装lgraph_import？我在官方文档里没有找到
> 
> 我的是在这个目录，希望对你有帮助 ![image](https://user-images.githubusercontent.com/86821930/228740617-97cd0445-b873-42e1-9c9c-e566ba2ca49d.png)

我的是在这个目录，希望对你有帮助 ![image](https://user-images.githubusercontent.com/86821930/228740617-97cd0445-b873-42e1-9c9c-e566ba2ca49d.png)

你好，我在我的tugraph容器里找到了这个目录，但是我应该怎么使用lgraph_import这个工具呢？我输入./lgraph_import --online false -help，底下报错Illegal instruction

**Comment by knightast** [comment]
lgraph_import --online 0 --help
这个挺正常的，具体是啥错？是在原来的路径里跑的么？

**Comment by qishipengqsp** [comment]
此Issue已保持4个月不活跃状态，先关闭，如有问题可以再次开启。
