### ISSUE TITLE
locate_node_by_indexed_prop和locate_node_by_vid优化bug

### ISSUE THREAD

**Issue by seijiang** [TuGraph-family/tugraph-db#190]
* locate_node_by_indexed_prop和locate_node_by_vid优化bug
    * 对于如下cypher
    ```
    match (n) where n.id=1 and n.id=2 or n.id=3 return n
    match (n) where id(n)=1 and id(n)=2 or id(n)=3 return n
    ```
    * 会发现返回结果并不为空,会返回和如下cypher一样的结果
    ```
    match (n) where n.id=1 or n.id=2 or n.id=3 return n
    match (n) where id(n)=1 or id(n)=2 or id(n)=3 return n
    ```
    * 这是因为在优化的时候并没有判断filter的logical op是否全为or,只判断了第一层的logical op,即最右边的logical op是否为or

**Comment by spasserby** [comment]
确实有问题，locate_node_by_indexed_prop和locate_node_by_vid实现的问题
它们本意是打算优化 exprA || exprB || exprC这种形式，但是在检查这种形式的错了
`
while (!filter->Left()->IsLeaf()) {
    filter = filter->Left();
    ...
}
`
要在`filter = filter->Left();`后面再检查一下Left的类型以及符号
`
if (filter->Type() != lgraph::Filter::BINARY ||
    filter->LogicalOp() != lgraph::LBR_OR) {
    return false;
}
`

**Comment by spasserby** [comment]
https://github.com/TuGraph-family/tugraph-db/commit/3a2cfb9c5ca54c63defeee22b93f216d16420948

**Comment by qishipengqsp** [comment]
此Issue已保持3个月不活跃状态，先关闭，如有问题可以再次开启。
