### ISSUE TITLE
运行lgraph_import命令报错

### ISSUE THREAD

**Issue by cptrailblazer** [TuGraph-family/tugraph-db#193]
![image](https://user-images.githubusercontent.com/108346856/230525658-9a2558d1-654d-4689-b934-9c1d8470afff.png)
我尝试使用lgraph_import数据导入工具，但是遇到了Illegal instruction报错，这个应该怎么解决呢？

**Comment by cptrailblazer** [comment]
我是在容器里面运行命令的

**Comment by qishipengqsp** [comment]
这是一个兼容性问题，最近发现并且修复过。用的是哪个版本的镜像，拉一下最新的镜像试试？

**Comment by qishipengqsp** [comment]
此Issue已保持3个月不活跃状态，先关闭，如有问题可以再次开启。 @cptrailblazer
