### ISSUE TITLE
lgraph_import导入官网示例数据报错

### ISSUE THREAD

**Issue by cptrailblazer** [TuGraph-family/tugraph-db#194]
![image](https://user-images.githubusercontent.com/108346856/231031512-c098a7ef-30d2-43ca-9bd4-3d83f782b943.png)
使用tugraph的lgraph_import工具导入官网文档中关于演员和电影的示例数据时，报错no vid for actor，但是我检查了一下，import.conf里面配置了actor的主键是aid啊。应该怎么解决呢？
![image](https://user-images.githubusercontent.com/108346856/231031844-3ed8720c-f125-4130-918b-312cbd164d08.png)

**Comment by knightast** [comment]
TuGraph的版本是多少？你用的是repo里的代码么？ https://github.com/TuGraph-family/tugraph-db/tree/master/demo/movie

vid一般表示内部的vertex id，schema中的边的SRC_ID和DST_ID能匹配上就行

**Comment by lipanpan03** [comment]
看报错日志，有可能是您import.conf配置文件的header参数配置的有问题。header如果设置的不正确的话，可能会导致roles.csv这个边文件导入的时候把表头也当作一条边导入了，建立边时把actor这个列名当成了数据，就会报no vid for actor，因为actor类型的点中不存在一个aid（主键）为"actor"的点。
![image](https://user-images.githubusercontent.com/41904587/231080593-79bcdd0e-6bea-4959-a91b-3aab9565c8f5.png)

**Comment by cptrailblazer** [comment]
> 看报错日志，有可能是您import.conf配置文件的header参数配置的有问题。header如果设置的不正确的话，可能会导致roles.csv这个边文件导入的时候把表头也当作一条边导入了，建立边时把actor这个列名当成了数据，就会报no vid for actor，因为actor类型的点中不存在一个aid（主键）为"actor"的点。 ![image](https://user-images.githubusercontent.com/41904587/231080593-79bcdd0e-6bea-4959-a91b-3aab9565c8f5.png)

你好，根据你的提示，我已经完成了导入，但是为什么我在tugraph的可视化界面还是没有看到我导入的数据呢？
![image](https://user-images.githubusercontent.com/108346856/231087108-09c1914e-8f14-4da4-bbd8-508439e2f366.png)
![image](https://user-images.githubusercontent.com/108346856/231087174-4a962fed-a2ba-4d69-a8ef-ee937a9f66e4.png)

**Comment by cptrailblazer** [comment]
> 离线导入数据之后需要重启服务，您重启server了吗？

我确认重启过容器了，但还是没有显示数据。是我的命令写的有问题吗？

**Comment by qishipengqsp** [comment]
此Issue已保持3个月不活跃状态，先关闭，如有问题可以再次开启。

**Comment by qishipengqsp** [comment]
此Issue已保持3个月不活跃状态，先关闭，如有问题可以再次开启
