### ISSUE TITLE
Tugraph有没有导入三元组的办法

### ISSUE THREAD

**Issue by cptrailblazer** [TuGraph-family/tugraph-db#195]
1.目前Tugraph可视化界面只能先导入节点，再导入关系，需要定义好csv文件的映射关系
2.lgraph_import数据导入工具也只能先定义好import.conf,导入节点和关系
有没有按照三元组导入数据的办法呢？

**Comment by GongChangYan** [comment]
目前应该是只有import.conf这一种形式的

**Comment by cptrailblazer** [comment]
> 目前应该是只有import.conf这一种形式的

这样确实不咋方便，尤其是在从其它图数据库迁移数据的时候。

**Comment by knightast** [comment]
同一份文件可以被读多遍，点、边都从同一份文件读。

**Comment by qishipengqsp** [comment]
此Issue已保持3个月不活跃状态，先关闭，如有问题可以再次开启。 @cptrailblazer
