### ISSUE TITLE
java pom.xml 文件引入tugraph依赖打包运行出现 找到多个名为spring_web的片段

### ISSUE THREAD

**Issue by BNingliu** [TuGraph-family/tugraph-db#197]
> pom.xml依赖

`
<dependency>
            <groupId>com.antgroup.tugraph</groupId>
            <artifactId>tugraph-java-rpc-client</artifactId>
            <version>0.0.1</version>
</dependency>
`

> 项目打成war包

> 放在tomcat9中运行出现

Caused by: java.lang.IllegalArgumentException: 找到多个名为spring_web的片段。这是不合法的相对排序。有关详细信息，请参阅Servlet规范的第8.2.2 2c节。考虑使用绝对排序

**Comment by qishipengqsp** [comment]
spring依赖已经清理，详细请看：
https://github.com/TuGraph-family/tugraph-db/issues/247
