### ISSUE TITLE
How to handle DateTime property in TuGraph by Cypher

### ISSUE THREAD

**Issue by frank-zsy** [TuGraph-family/tugraph-db#203]
I would like to use Cypher to access edge data with a DateTime type property, like in Neo4j, we can use

```
MATCH ()<-[a:action]-() WHERE datetime({year: 2023, month:3}) > datetime(a.time) >= datetime({year:2023,month:2}) RETURN a
```

to find out all the `action` edges with `time` property during 2023.2. or if `time` is a DateTime type, we can use

```
MATCH ()<-[a:action]-() WHERE a.time.year=2023 AND a.time.month=2 RETURN a
```

But above 2 methods will throw `Function not implemented yet` exception in TuGraph.

So how can I use DateTime type property in `where` clause to filter the result, I can not find any documentation in website.

**Comment by frank-zsy** [comment]
Further more, if I create an index on the property, how can I use the index in Cypher? Like will `a.time.year` takes the advantage of the index? Or we need to use `datetime({year: 2023, month:3}) > datetime(a.time) >= datetime({year:2023,month:2})` to use the index?

**Comment by wangtao9** [comment]
> I would like to use Cypher to access edge data with a DateTime type property, like in Neo4j, we can use
> 
> ```
> MATCH ()<-[a:action]-() WHERE datetime({year: 2023, month:3}) > datetime(a.time) >= datetime({year:2023,month:2}) RETURN a
> ```
> 
> to find out all the `action` edges with `time` property during 2023.2. 

In TuGraph,  you can currently use the following query
```
MATCH ()<-[a:action]-() WHERE datetime(“2023-03-01 00:00:00”) > a.time >= datetime("2023-02-01 00:00:00") RETURN a
```
Currently, OpenCypher only supports this construction method (`YYYY-MM-DD HH:MM:SS`) for datetime. So I will recommend using timestamp for now.



> or if `time` is a DateTime type, we can use
> 
> ```
> MATCH ()<-[a:action]-() WHERE a.time.year=2023 AND a.time.month=2 RETURN a
> ```
> 
> But above 2 methods will throw `Function not implemented yet` exception in TuGraph.
> 
> So how can I use DateTime type property in `where` clause to filter the result, I can not find any documentation in website.

The equivalent function is `datetimeComponent`, for example, `datetimeComponent(1582705717, 'year')` will return the year of the given timestamp.

**Comment by frank-zsy** [comment]
Thanks for the reply, it will be really helpful to put these information into documentation.

**Comment by wangtao9** [comment]
> Thanks for the reply, it will be really helpful to put these information into documentation.

@antkiller996 Include this in the new document.
