### ISSUE TITLE
事务相关

### ISSUE THREAD

**Issue by nnwai** [TuGraph-family/tugraph-db#204]
文档说支持高效OLTP，请问事务是怎么设置的，默认一行cypher以事务的模式插入吗，客户端是否支持多语句事务

**Comment by knightast** [comment]
对cypher是一条一个事务，也可以用procedure接口自己控制事务的开启、结束、中断

**Comment by qishipengqsp** [comment]
此Issue 2个月未响应，先关闭，如有问题可以再次开启 @nnwai
