### ISSUE TITLE
修改点的标签

### ISSUE THREAD

**Issue by wanghang-github** [TuGraph-family/tugraph-db#236]
**Describe the bug**
我想修改指定节点的标签，但是出现了报错

**To Reproduce**
1. 部署了Tugraph的单机社区版
2. 导入了csv文件
3. 运行代码`match(n:instance) where n.value = 'MINE' remove n:instance set n:MINE;`

error_message: "CypherException: Function not implemented yet: visitOC_RemoveItem at :417"

**Expected behavior**
期待节点的标签得到修改

**Screenshots**
![image](https://github.com/TuGraph-family/tugraph-db/assets/69884447/8aaf9681-7fd4-4c79-a085-2e0ab7dc92ae)

**Environment:**
 - OS: [e.g. Ubuntu 18.04]
 - CPU: [e.g. Intel Xeon xxxx]
 - Compiler: [e.g. GCC 8.0]

**Additional context**

**Comment by spasserby** [comment]
目前来说Remove不支持删除一个点的标签/LABEL，同时因为strong-schema的原因，直接修改一个点的标签也不是很自然的事情。

不过从实现的角度，可以考虑“创建+删除”的方式来“修改”指定节点的标签，可以参考下面的例子：
```Cypher
MATCH (n: instance {name:'Liam Neeson'})
CREATE (m:MINE {id:a.id, name:a.name})
WITH n
DELETE n
```

**Comment by qishipengqsp** [comment]
The issue is closed due to inactivity. Please feel free to create a new one if you have more questions. And please star this repo if you find it useful! Thanks!

此issue由于长期不活跃被关闭。如有任何问题，可另开 issue 并提供更多信息。如果这个项目帮助到你，可以在仓库右上角 star 一下，感谢你的支持!
