### ISSUE TITLE
Python存储过程文档中CreateWriteTxn与实际实现不符

### ISSUE THREAD

**Issue by gtahoo** [TuGraph-family/tugraph-db#244]
python存储过程文档上CreateWriteTxn有2个参数:optimistic和async, 我看源码当中只绑了一个参数；我刚才写代码看文档CreateWriteTxn(False, False)会报错，翻源码改成传一个参数就可以了。
![9956a52f13f3f877366201f0b7823cac](https://github.com/TuGraph-family/tugraph-db/assets/133954629/8a148270-31f2-46d6-a61c-beca1ef1d0b0)
![eec65a2020795218e9fb960d6ab9d943](https://github.com/TuGraph-family/tugraph-db/assets/133954629/0be9ac20-36c5-426d-a7c7-8bf9d086d966)
 by 俞忠静

**Comment by knightast** [comment]
感谢提出，这个是文档不一致，我们更新下

**Comment by gtahoo** [comment]
fixed after 3.6.0
