### ISSUE TITLE
希望有token最佳实践的文档

### ISSUE THREAD

**Issue by gtahoo** [TuGraph-family/tugraph-db#245]
由于TuGraph的token设计机制默认1小时会超时，是否有什么好的办法？by 俞忠静

**Comment by knightast** [comment]
可以在lgraph_server启动的时候指定token不会过期，官方的client包含了token自动刷新机制，自己写的就得手动去调用refresh了

**Comment by knightast** [comment]
写一个token的文档，介绍所有与 token 有关的事，使用不同的client（rpc/rest/browser）是怎么处理token的。
文档放在：https://github.com/TuGraph-family/tugraph-db/tree/master/doc/zh-CN/source/5.developer-manual/8.other

**Comment by qishipengqsp** [comment]
The issue is closed due to inactivity. Please feel free to create a new one if you have more questions. And please star this repo if you find it useful! Thanks!
此issue由于长期不活跃被关闭。如有任何问题，可另开 issue 并提供更多信息。如果这个项目帮助到你，可以在仓库右上角 star 一下，感谢你的支持!
