### ISSUE TITLE
节点属性存储json字符串异常

### ISSUE THREAD

**Issue by zhang-jinqi** [TuGraph-family/tugraph-db#248]
springboot引入ogm来进行存储json字符串，会出现解析错误：com.antgroup.tugraph.TuGraphDbRpcException: CypherException: ParserException: line 1:194 no viable alternative at input 'CREATE (n0:OntologyRelDTO{crTime:"2023-07-09",crUser:"trs_cai",deletedFlag:0,ontologyId:"40289781892e7c9901892e7d47790000",ontologyRelationId:"40289781893888930189388a92d80001",sourceConcept:"{"nodeName'
![1688873310073](https://github.com/TuGraph-family/tugraph-db/assets/79257896/fcde90af-3a83-44d0-922c-38e05e260763)
![1688873310043](https://github.com/TuGraph-family/tugraph-db/assets/79257896/b67f7d13-9512-43da-badc-a1658ba7a125)
![image](https://github.com/TuGraph-family/tugraph-db/assets/79257896/4d54beb9-c203-46b9-99ce-477429a5d9f9)

**Comment by liubingyelby** [comment]
感谢提问，ogm还无法很好的支持JSON格式的数据，我们将会尝试在下一个版本中修复这个问题。
方便的话可以提供更多的信息吗？比如您是如何创建的这个带有json数据的类?

**Comment by qishipengqsp** [comment]
The issue is closed due to inactivity. Please feel free to create a new one if you have more questions. And please star this repo if you find it useful! Thanks!
此issue由于长期不活跃被关闭。如有任何问题，可另开 issue 并提供更多信息。如果这个项目帮助到你，可以在仓库右上角 star 一下，感谢你的支持!
