### ISSUE TITLE
github主页上的编译流程有问题

### ISSUE THREAD

**Issue by AK-tu** [TuGraph-family/tugraph-db#264]
提个建议，github主页上的编译流程有问题。第一，代码库里的deps文件夹连接到了其他两个代码库，这个在git clone的时候是clone不下来的，所以用户就需要手动去把这两个库clone下来。第二，make之前需要有一个脚本把所有的依赖库都安装好，我在make的时候一直出问题，就是经常会报没有什么什么库这种，给人的体验很不好，用户如果遇到这种问题很容易就放弃的。

**Comment by jasinliu** [comment]
同踩坑，主页编译过程已经修改了~ #263

第一个，可以加个参数 --recursive
第二个，库安装可以参考docker，更推荐直接使用docker

**Comment by AK-tu** [comment]
> 同踩坑，主页编译过程已经修改了~ #263
> 
> 第一个，可以加个参数 --recursive 第二个，库安装可以参考docker，更推荐直接使用docker

666

**Comment by AK-tu** [comment]
> 同踩坑，主页编译过程已经修改了~ #263
> 
> 第一个，可以加个参数 --recursive 第二个，库安装可以参考docker，更推荐直接使用docker

**Comment by Codewulan** [comment]
@jasinliu @AK-tu 请问你们编译遇到了缺少package.json的问题吗？
![image](https://github.com/user-attachments/assets/3e239378-280d-4283-a8b7-0ea1d1654a0e)

**Comment by jasinliu** [comment]
> @jasinliu @AK-tu 请问你们编译遇到了缺少package.json的问题吗？

是不是你clone的时候没带`--recursive`，没有把submodule clone下来，这个文件夹应该都是空的。
可以`git submodule update --init`试试

**Comment by Codewulan** [comment]
> > @jasinliu @AK-tu 请问你们编译遇到了缺少package.json的问题吗？
> 
> 是不是你clone的时候没带`--recursive`，没有把submodule clone下来，这个文件夹应该都是空的。 可以`git submodule update --init`试试

哦哦，原来如此，多谢哈
