### ISSUE TITLE
想使用一下这边的鲁汶社区发现算法

### ISSUE THREAD

**Issue by wanghang-github** [TuGraph-family/tugraph-db#272]
目前的本地单机版并不支持这个图算法的实现，确实想用的话怎么办呢，有没有什么替代的方法

**Comment by Clarkclk** [comment]
Louvain算法我们计划近期会开源

**Comment by qishipengqsp** [comment]
The issue is closed due to inactivity. Please feel free to create a new one if you have more questions. And please star this repo if you find it useful! Thanks!
此issue由于长期不活跃被关闭。如有任何问题，可另开 issue 并提供更多信息。如果这个项目帮助到你，可以在仓库右上角 star 一下，感谢你的支持!
