### ISSUE TITLE
使用lgraph_import 离线导入大量数据会导致内存使用过多而被系统杀死

### ISSUE THREAD

**Issue by 19wyy** [TuGraph-family/tugraph-db#274]
1.  将要导入的数据存放在磁盘中进行导入会导致一个错误
[2023-Aug-10 02:06:30.809693] [INFO] - An error occurred during import:  vid_sst_writer.Put error, Invalid argument: Keys must be added in strict ascending order
![b03747a9e401e2a04d553bc7c3da53a7](https://github.com/TuGraph-family/tugraph-db/assets/86821930/c2d4a546-1ed6-47ec-8ae2-9c2bda35b2cc)
2. 将数据--keep_vid_in_memory 设置为true会导致数据导入过程因为使用内存过多而被杀死
![b48f24f18f77e2f75494d0f9df9d073d](https://github.com/TuGraph-family/tugraph-db/assets/86821930/5bf522c9-d973-4725-b43f-703f73182d54)
数据大概有 400G左右 使用的服务器有512G的内存，但是该导入进程还是被杀死
3. 有没有什么能够解决大量离线导入图数据库的时候，减少内存的占用

**Comment by ljcui** [comment]
keep_vid_in_memory 为false导入失败，是因为点数据有重复，目前没过滤好，下个版本会修复下。
可以先用其他办法把数据清洗下，然后再试试 keep_vid_in_memory 为false，是否还有报错。

**Comment by ljcui** [comment]
4.0版本 这个问题已经修复。
