### ISSUE TITLE
使用lgraph_import在线导入数据时,无法正常导入数据

### ISSUE THREAD

**Issue by 19wyy** [TuGraph-family/tugraph-db#276]
1.在线导入数据时会卡住不动
![cf7d3703c2946d731206cb2630b3d77c](https://github.com/TuGraph-family/tugraph-db/assets/86821930/657302b2-e57e-4e1e-a67b-ae789c306f96)
![0f4912214d68eb6e9fd6b73d883d8bfb](https://github.com/TuGraph-family/tugraph-db/assets/86821930/8291d73e-7cd7-4967-a428-49dccb99e247)
数据无法正常导入，报了一个这样的错误：
20230811045804.808: An error occurred during import:
20230811045804.808:   connection fails [Failed to read HTTP status line]
![26cf6430105906c598fd418feb6697dd](https://github.com/TuGraph-family/tugraph-db/assets/86821930/fec59f67-3459-42b5-8e28-5de66b0d5f00)

**Comment by ljcui** [comment]
在线导入一次的批量比较大，在加上用的的机械硬盘，单个导入请求耗时太长，导致超时。
换成SSD后不再超时，顺利导入。
