### ISSUE TITLE
tugraph-db编译安装时关于antlr4的报错

### ISSUE THREAD

**Issue by lsl031** [TuGraph-family/tugraph-db#303]
安装环境为redhat8.8 x86 64位操作系统。
采用源码编译安装的方式尝试进行tugraph-db，之前按照cetos8编译版本的dockerfile来进行了各模块的准备。其中在配置Antlr4 时，由于安装的环境为离线环境，没法连接到互联网，所以都是采用离线安装的方式进行的，基本都没问题，其中在配置antlr4时，采用如下方式进行的操作（不知道是否有什么问题）
1、下载 antlr4-4.13.0.tar.gz和antlr4-4.13.0-complete.jar
2、执行antlr4的编译安装
tar zxf antlr4-4.13.0.tar.gz && cd antlr4-4.13.0/runtime/Cpp/ \
    && mkdir -p build && cd build \
    && cmake -DWITH_DEMO=0 -DANTLR_BUILD_CPP_TESTS=0 -DCMAKE_CXX_STANDARD=17 -DCMAKE_CXX_FLAGS=-fPIC -DANTLR4_INSTALL=1 -DCMAKE_INSTALL_PREFIX=/usr/local .. \
    && make ${JFLAG} && make install 
3、cp antlr4-4.13.0-complete.jar /usr/local/bin \
    && chmod 755 /usr/local/bin/antlr4-4.13.0-complete.jar 

之后全部配置完后执行
1、deps/build_deps.sh
2、$ mkdir build && cd build
3、cmake的命令为cmake ..  -DENABLE_PREDOWNLOAD_DEPENDS_PACKAGE=1
在这里有如下报错。
CMake Error at /usr/local/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
Could NOT find Antlr4 (missing: Antlr4_GENERATOR) (Required is at least
version "4.13.0")
Call Stack (most recent call first):
/usr/local/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
deps/geax-front-end/cmake/Modules/FindAntlr4.cmake:161 (find_package_handle_standard_args)
deps/geax-front-end/CMakeLists.txt:111 (find_package) 

请帮看看是否能指导解决。谢谢！

**Comment by spasserby** [comment]
是antlr4的环境没有配置成功，不仅仅需要antlr4的c++ runtime，还需要antlr4-4.13.0-complete.jar。
你的安装命令缺少了mvn package，所以缺少了antlr4-4.13.0-complete.jar。

1.如何正确配置antlr4环境，可以参考：
https://github.com/TuGraph-family/tugraph-db/blob/master/ci/images/tugraph-compile-centos8-Dockerfile

2.在离线环境怎么去做mvn package
在其它机器上制作antlr4-4.13.0-complete.jar，拷贝到离线机器的合适位置（/usr/local/bin）

**Comment by lsl031** [comment]
谢谢回复。
tar zxf antlr4-4.13.0.tar.gz && cd antlr4-4.13.0/runtime/Cpp/
&& mkdir -p build && cd build
&& cmake -DWITH_DEMO=0 -DANTLR_BUILD_CPP_TESTS=0 -DCMAKE_CXX_STANDARD=17 -DCMAKE_CXX_FLAGS=-fPIC -DANTLR4_INSTALL=1 -DCMAKE_INSTALL_PREFIX=/usr/local ..
&& make ${JFLAG} && make install

这里是有这一步的、离线下载了这个包并且有拷贝。
3、cp antlr4-4.13.0-complete.jar /usr/local/bin
&& chmod 755 /usr/local/bin/antlr4-4.13.0-complete.jar


c++、python、protobuf等等都是按照docerfile的命令执行安装成功了的。

**Comment by lsl031** [comment]
更新下进度，下载的antlr-4.13.0-complete.jar 这个文件重命名为antlr4-4.13.0-complete.jar就可以了。但是出现了其他的cython的错误，我再看看

**Comment by qishipengqsp** [comment]
The issue is closed due to inactivity. Please feel free to create a new one if you have more questions. And please star this repo if you find it useful! Thanks!
此issue由于长期不活跃被关闭。如有任何问题，可另开 issue 并提供更多信息。如果这个项目帮助到你，可以在仓库右上角 star 一下，感谢你的支持!
