### ISSUE TITLE
Guide to version upgrade

### ISSUE THREAD

**Issue by CAQ** [TuGraph-family/tugraph-db#307]
When upgrading from v3.x to v4, data needs to be export and import back again.
Expect documents to explicitly showing how to do the upgrade, step by step.
Many users meet this issue, and asked in our groups.

**Comment by knightast** [comment]
Here is doc: https://tugraph-db.readthedocs.io/en/latest/7.best-practices/3.data_migration.html

**Comment by CAQ** [comment]
I'd prefer a more straight-forward (step-by-step) guide to version upgrade, instead of only one of the steps.
