### ISSUE TITLE
数据文件目录的文档说明

### ISSUE THREAD

**Issue by knightast** [TuGraph-family/tugraph-db#315]
1. 在文档某个地方说下默认的data目录
2. docker启动时，一般会加上路径映射 https://tugraph-db.readthedocs.io/zh-cn/latest/3.quick-start/1.preparation.html#docker

**Comment by knightast** [comment]
检查下阿里云计算巢的部署是否做了文件目录的映射

**Comment by qishipengqsp** [comment]
等下个版本修复

**Comment by qishipengqsp** [comment]
4.1.0版本已修复：https://computenest.console.aliyun.com/service/instance/create/cn-hangzhou?type=user&ServiceId=service-7b50ea3d20e643da95bf&isTrial=true
