### ISSUE TITLE
Add a golang method for calling rpc.

### ISSUE THREAD

**Issue by a3sroot** [TuGraph-family/tugraph-db#317]
Compatible with the golang for calling rpc

**Comment by knightast** [comment]
No golang bprc client yet :(

The rpc and rest server of TuGraph both using brpc, therefore we'd better using brpc client.

Currently, the brpc client of TuGraph support c++/java/python. C++ using brpc official client, while java using baidu supported client (https://github.com/baidu/starlight). Python using python11 of c++ client.

Anyway, rest client can be much easier supported by any language.

**Comment by a3sroot** [comment]
Why not use GRPC?

**Comment by qishipengqsp** [comment]
tugraph-db uses braft as its consistency protocol, which binds brpc as its embedded rpc. So we use brpc as default between client and server. Moreover, brpc is a good choice besides grpc.

**Comment by qishipengqsp** [comment]
Now tugraph-db supports bolt protocol, which enables us to use some open-source client from Neo4j community. If you prefer Golang, you can try this at https://github.com/TuGraph-family/tugraph-db/blob/master/demo/Bolt/go_example.go

**Comment by qishipengqsp** [comment]
We hope we help you on this issue. This issue will be closed as it is supposed to be solved. If you have any more questions, please feel free to reopen it.
