### ISSUE TITLE
Generate JPG image based on query

### ISSUE THREAD

**Issue by a3sroot** [TuGraph-family/tugraph-db#318]
Generate JPG image based on query,Converting graph data queries to images.

**Comment by a3sroot** [comment]
<img width="149" alt="image" src="https://github.com/TuGraph-family/tugraph-db/assets/81551286/cacf0bc3-be4e-480b-abe2-8292979f878a">
Implemented via back-end api

**Comment by knightast** [comment]
How to specify the image layout backend can be a problem, such as color, text to display, layout style. 

This kind of interactive specification can be easily done in the web, which is how we support currently.

Do you have any interface suggestions?

**Comment by qishipengqsp** [comment]
The issue is closed due to inactivity. Please feel free to create a new one if you have more questions. And please star this repo if you find it useful! Thanks!
此issue由于长期不活跃被关闭。如有任何问题，可另开 issue 并提供更多信息。如果这个项目帮助到你，可以在仓库右上角 star 一下，感谢你的支持!
