### ISSUE TITLE
[dependency] TuGraph Browser - Failed to compile (cpp) plugin

### ISSUE THREAD

**Issue by Hexrt** [TuGraph-family/tugraph-db#32]
**Describe the bug**

TuGraph Browser Failed to compile cpp plugin. Caused by not found **'json.hpp'** file.

**To Reproduce**
1. Flow 'quick-start', use docker to pull image.(bash `docker pull tugraph/tugraph-db-centos7`)
2. Run with bash 
  `docker run -d -p 7070:7070 -p 9090:9090 --name tugraph_demo tugraph/tugraph-db-centos7 lgraph_server`
3. Browser `http://xxxx:7070`. And login.
4. Click “帮助” -> “快速上手” -> “一键安装插件”. Then click left menu "插件".
5. **See error** (Failed to install cpp plugin)

**OR** 
1. Click "帮助" -> "插件", download `khop.cpp`
2. Click left menu "插件" -> "添加插件", choose your file `khop.cpp` and type `cpp`...
3. Click "创建", **See error**
`Failed to compile plugin. Stdout:---- Stderr:---- /var/lib/lgraph/data/95AE5128C290CC84F2BEBE0662EC1217/_cpp_plugin_/_fma_CPP1714636915_1662686797376047776.tmp/_fma_CPP.cpp:11:22: fatal error: ./json.hpp: No such file or directory #include "./json.hpp" ^ compilation terminated.`

**Expected behavior**
Install cpp plugin `khop.cpp` successfully.

**Screenshots**
![image](https://user-images.githubusercontent.com/57286895/189254300-8c4f1c14-dd9e-4069-8eb5-358b4a61cba8.png)

**Environment:**
 - OS: CentOS  7.9 64bit
 - CPU: Intel(R) Xeon(R) Platinum 8163 CPU @ 2.50GHz
 - Compiler: 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC)

**Additional context**
nope

**Comment by KingSkyLi** [comment]
请问当前使用的版本号是多少，3.3.2版本以后可视化自带的plugin已经替换，如果有其他问题请留言

**Comment by qishipengqsp** [comment]
此Issue已保持8个月不活跃状态，先关闭，如有问题可以再次开启。
