### ISSUE TITLE
使用datax，同步数据报错MDB_MAP_FULL

### ISSUE THREAD

**Issue by cooler810** [TuGraph-family/tugraph-db#320]
使用datax同步文件中的数据，报错了：
KvException: MDB_MAP_FULL: Environment mapsize limit reached
tugraph版本：[v4.0.1]

**Comment by austfish** [comment]
请问tugraphwriter 这个插件在哪下载

**Comment by ljcui** [comment]
> 使用datax同步文件中的数据，报错了： KvException: MDB_MAP_FULL: Environment mapsize limit reached tugraph版本：[v4.0.1]

有多少数据量？

**Comment by ljcui** [comment]
> 请问tugraphwriter 这个插件在哪下载

https://github.com/TuGraph-family/DataX

**Comment by cooler810** [comment]
找到问题了，新建图的时候指定的最大存储空间太低了。增加后没有错误了
