### ISSUE TITLE
Cypher 导致 lgraph_server 崩溃

### ISSUE THREAD

**Issue by knightast** [TuGraph-family/tugraph-db#322]
执行一个Cypher查询，前端一直转圈，后台看TuGraph已经挂掉了

match (m:Flag)-[r:flag_company]->(n:Company) where n.nsrsbh='xxxx' and r.lrsj >=1 and r.lrsj<=100 return sum(r.amount)

From: 社区反馈

**Comment by spasserby** [comment]
优化规则对执行计划调整出现纰漏：
1.修复错误的执行计划调整过程
2.对修改执行计划添加检查

**Comment by knightast** [comment]
已修复
https://github.com/TuGraph-family/tugraph-db/commit/07e4d178a245057d35b3ed3c02ecc45f6de4d290
