### ISSUE TITLE
 Docker run error tugraph-runtime-arm64v8-centos7, Macbook air m2 chip, docker desktop version 4.24.2, macos Ventura 13.5

### ISSUE THREAD

**Issue by zrg1993** [TuGraph-family/tugraph-db#326]

**Comment by GongChangYan** [comment]
```
docker pull tugraph/tugraph-runtime-arm64v8-centos7:4.0.1
docker run -dt -p 7070:7070 --name tugraph_demo ttugraph/tugraph-runtime-arm64v8-centos7:4.0.1
docker exec -it tugraph_demo bash
lgraph_server -d start
```
Everything works fine when I execute the above command
![M2docker](https://github.com/TuGraph-family/tugraph-db/assets/50070084/4bd16092-477b-4da9-ae4a-2a058d493c34)

environments:
* Apple M2 Pro
* docker desktop: 24.0.6 
* macos: Ventura 13.2.1

Can you post your commands and error logs?

**Comment by zrg1993** [comment]
Thanks for checking the issue. I use the script for you and it works well. I think there was some issue in my issue.
I found one spelling miss 'ttugraph'  in your command. Thanks again.
