### ISSUE TITLE
增加对节点属性的操作

### ISSUE THREAD

**Issue by includewins0ck2** [TuGraph-family/tugraph-db#332]
比如,neo4j支持匹配到一个节点后,set 属性,比如 set test = '测试',那么这个匹配到的节点,就多了一个test属性,某些情况下很好用,建议加上.

**Comment by knightast** [comment]
给一句cypher的完整语句？

**Comment by ljcui** [comment]
> 给一句cypher的完整语句？

一楼的说的意思是 schemaless

**Comment by qishipengqsp** [comment]
目前暂无明确计划支持Schemaless的操作。

**Comment by qishipengqsp** [comment]
The issue is closed due to inactivity. Please feel free to create a new one if you have more questions. And please star this repo if you find it useful! Thanks!
此issue由于长期不活跃被关闭。如有任何问题，可另开 issue 并提供更多信息。如果这个项目帮助到你，可以在仓库右上角 star 一下，感谢你的支持!
