### ISSUE TITLE
doc生成逻辑需要优化

### ISSUE THREAD

**Issue by knightast** [TuGraph-family/tugraph-db#333]
文档包括：静态文档（./docs），动态文档（procedure api文档）

需要：
1. 文档能整体在 readthedocs 页面展示，https://tugraph-db.readthedocs.io/zh_CN/latest/
2. 能够通过ci保证文档可编译

整体流程是通的，但有些问题：
1. 手动执行 cpplint/doc_gen.sh 会删文件，不能重复执行，逻辑需要更新
2. https://github.com/TuGraph-family/tugraph-db/blob/master/docs/zh-CN/source/conf.py 中有硬编码版本3.5.0，so的更新逻辑是啥？

**Comment by lipanpan03** [comment]
https://github.com/TuGraph-family/tugraph-db/pull/337 收到，已修改文档生成逻辑：
1. 在删除文件之前先判断，文档生成在本地环境和read_the_docs环境中均能重复执行
2. 将doc生成依赖文件夹改为doc_deps，删除硬编码3.5.0

**Comment by qishipengqsp** [comment]
Fixed
