### ISSUE TITLE
支持批量查询Vertex与相关的edge吗

### ISSUE THREAD

**Issue by zhang-jinqi** [TuGraph-family/tugraph-db#335]
在官方文档中，使用cypher操作vertex和edge标签时，没有找到可以批量获取vertex以及相关edge信息
的api，请问支持批量查询Vertex与相关的edge吗

**Comment by qishipengqsp** [comment]
可以用相关的写法包括：`Match (n)-[e]->() WHERE n.id=0 RETURN e` 就是默认返回所有的e，如果想要过滤e，就可以加入`where e.amount > 500`子句

**Comment by qishipengqsp** [comment]
如有问题，可以再次open这个issue
