### ISSUE TITLE
TuGraphClient连不上server

### ISSUE THREAD

**Issue by GongChangYan** [TuGraph-family/tugraph-db#338]
在docker中启动server后使用TuGraphClient连不上但是浏览器前端可以正常访问

docker：
```
docker run -d -p 7070:7070 -p 9090:9090 --name tugraph_demo tugraph/tugraph-runtime-centos7 lgraph_server
```

环境：
* 镜像：tugraph/tugraph-runtime-centos7:4.0.1
* client：[fbee7ab](https://github.com/TuGraph-family/tugraph-db/commit/fbee7ab918fd9f9414db8340b4fd278dc639eb3a)
* 机器：windows11
* Python：python3.10

**Comment by qishipengqsp** [comment]
Fixed internally
