### ISSUE TITLE
tugraph-db/include/lgraph/lgraph_types.h 文件中对unique_ptr的使用错误

### ISSUE THREAD

**Issue by jiazhenjiang** [TuGraph-family/tugraph-db#339]
在cpp文件中引用此头文件，编译时报错如下
![截屏2023-12-06 下午4 37 06](https://github.com/TuGraph-family/tugraph-db/assets/16101364/3ebe0d7b-0ff2-4ea6-ade0-83f12e6b8c44)

**Comment by knightast** [comment]
在compile docker里也会出错

**Comment by hanwen-sun** [comment]
这里大概率是需要将某个地方的c++14编译升级为c++17.是在哪个compile docker中报错的?我复现一下

**Comment by jiazhenjiang** [comment]
这个问题的原因在于c++17标准中引入了copy elison规则，强制复制省略。在类Spatial中，没有定义拷贝构造函数，也没有将拷贝构造函数定义为delete，编译器生成的默认拷贝构造函数将成员挨个拷贝一遍，成员中有unique_ptr，此成员的拷贝构造函数被定义为delete，因此采用17之前的标准会报出这个错误。但在17标准中，因为copy elison规则，这个拷贝被省略了，因此编译通过，但这个写法严格来说是有问题的。应该要定义类Spatial的拷贝构造函数，要么定义为delete，要么显示去处理unique_ptr

**Comment by qishipengqsp** [comment]
Spatial类没有显示定义拷贝构造函数，内部成员unique_ptr的拷贝构造函数又被删除了，编译器自动生成的拷贝构造函数会有问题。

https://github.com/TuGraph-family/tugraph-db/blob/master/include/lgraph/lgraph_types.h#L852 这里拷贝构造就会存在调用被delete了的拷贝构造函数。


解决：使用move或者修改实现。
