### ISSUE TITLE
mis最大独立集算法运行长时间无结果

### ISSUE THREAD

**Issue by VPTT** [TuGraph-family/tugraph-db#340]
运行mis的standalone算法程序，尝试soc_Epinions、soc-LiveJournal1、twitterMPI数据集，都是处于一直长时间运行状态。

![image](https://github.com/TuGraph-family/tugraph-db/assets/44954836/18b48a9d-5552-4c7b-b2ef-9d169ffe597d)
![image](https://github.com/TuGraph-family/tugraph-db/assets/44954836/ed1b189b-1593-4b1e-afe2-b8abfc30f066)
![image](https://github.com/TuGraph-family/tugraph-db/assets/44954836/f25b5e0a-3178-4b37-a211-90c369665565)

**Comment by GongChangYan** [comment]
这个算法是适用于无向图的，在有向图上运行时需要加上参数`--make_symmetric 1`
之后会将这个参数的默认值设为1

**Comment by VPTT** [comment]
> 这个算法是适用于无向图的，在有向图上运行时需要加上参数`--make_symmetric 1` 之后会将这个参数的默认值设为1

我使用的指令是加上了make symmetric参数的./output/algo/mis_standalone --type text --input_dir /graph_data/twitter_rv.el --make_symmetric 1>> /graph_data/result/twitterRV_mis.txt

**Comment by GongChangYan** [comment]
> > 这个算法是适用于无向图的，在有向图上运行时需要加上参数`--make_symmetric 1` 之后会将这个参数的默认值设为1
> 
> 我使用的指令是加上了make symmetric参数的./output/algo/mis_standalone --type text --input_dir /graph_data/twitter_rv.el --make_symmetric 1>> /graph_data/result/twitterRV_mis.txt

在soc-LiveJournal1上加上make_symmetric后就正常结束了，twitter_rv这个数据能发一下吗

**Comment by qishipengqsp** [comment]
问题已修复，麻烦再试一下看看还有无问题
