### ISSUE TITLE
Cannot allocate memory in static TLS block when upload algorithm plugin

### ISSUE THREAD

**Issue by fanzhidongyzby** [TuGraph-family/tugraph-db#352]
** Issue **
When uploading the .so algorithm plugin, an error is reported :

```
Failed to load the DLL: /var/lib/lgraph/data/D4C2203EE5F7EF40A489D54A5912A317/cpp_plugin/_fma_kcore.so: cannot allocate memory in static TLS block
```

** Reproduction **
1. Uploading too many plugin .so files will lead to the above problem.
2. Even if the old plugins are uninstalled and new ones are uploaded, the same error will be reported.
3. Uninstalling all the old plugins and restarting the lgraphserver, then uploading will return to normal.

Preliminary judgment suggests that uploading too many algorithm plugins can lead to the inability to allocate memory in the TLS block, which may be caused by the loader cache not being released cleanly.

**Comment by qishipengqsp** [comment]
Duplicated in #347
