### ISSUE TITLE
希望能够支持返回数据进行脱敏

### ISSUE THREAD

**Issue by szlixg** [TuGraph-family/tugraph-db#368]
**Is your feature request related to a problem? Please describe.**
在查询出来的数据中，通过udf之类的方式，可以进行数据脱敏操作，脱敏规则，可选择，比如电话号码类型脱敏，身份证类型脱敏等
A clear and concise description of the problem.

**Describe the solution you'd like**

A clear and concise description of what you want to happen and any alternative solutions or features you've considered.

**Comment by qishipengqsp** [comment]
新增的substr()的函数是否可以满足需求？或者有参考样例么？
PR： #364
