### ISSUE TITLE
TuGraph Server stopped in Docker while reporting 'UpdateDerivedVars is too Busy!'

### ISSUE THREAD

**Issue by jqlin2019** [TuGraph-family/tugraph-db#374]
**Environment:**
- OS: Ubuntu 18.04.5 LTS
- TuGraph-DB Version 3.5.0
- Docker Image Version: tugraph/tugraph-runtime-centos7:3.5.0

**Describe the bug**
```
20240109080520.768: [StateMachine] bvar is busy at sampling for 2 seconds!
20240109084356.783: [StateMachine] GlobalUpdate is too busy!
20240109084453.686: [StateMachine] UpdateDerivedVars is too Busy!
```
I restarted the server after a few seconds.
The log was never seen before, what does that mean?
ls there too many update queries?

**Comment by lipanpan03** [comment]
How did you restart the server?

**Comment by lipanpan03** [comment]
> **Environment:**
> 
> * OS: Ubuntu 18.04.5 LTS
> * TuGraph-DB Version 3.5.0
> * Docker Image Version: tugraph/tugraph-runtime-centos7:3.5.0
> 
> **Describe the bug**
> 
> ```
> 20240109080520.768: [StateMachine] bvar is busy at sampling for 2 seconds!
> 20240109084356.783: [StateMachine] GlobalUpdate is too busy!
> 20240109084453.686: [StateMachine] UpdateDerivedVars is too Busy!
> ```
> 
> I restarted the server after a few seconds. The log was never seen before, what does that mean? ls there too many update queries?

You can see the similar [issue](https://github.com/apache/brpc/issues/1239) in brpc. These logs mean that the machine resources are too tight, causing the related threads of bvar::detail::SamplerCollector to be unable to obtain the cpu. So you can choose a machine with more resources.

**Comment by jqlin2019** [comment]
> You can see the similar https://github.com/apache/brpc/issues/1239 in brpc. These logs mean that the machine resources are too tight, causing the related threads of bvar::detail::SamplerCollector to be unable to obtain the cpu. So you can choose a machine with more resources.

Thanks for your help.
I just restarted the docker containter with command `docker restart containter_name`.
There were some resource-intensive programs running on the machine at that time, I will pay attention to them.
