### ISSUE TITLE
离线导入3亿带索引关系边报bad_alloc

### ISSUE THREAD

**Issue by yzjzgr** [TuGraph-family/tugraph-db#406]
Environment:

OS: [centos 7]
CPU: [Intel(R) Xeon(R) Platinum 8269CY CPU @ 2.50GHz 8 cores]
MEM: 32G
TuGraph-DB Version [e.g. 4.1.0]
standalone

**Describe the bug**
图schema:
{
  "schema": [
    {
      "label": "entity",
      "type": "VERTEX",
      "properties": [
        { "name": "primary_key", "type": "STRING" },
        { "name": "entity_type", "type": "STRING" },
        { "name": "entity_properties", "type": "STRING","optional": true }
      ],
      "primary": "primary_key"
    },
    {
      "label": "relation",
      "type": "EDGE",
      "properties": [
        { "name": "relation_type", "type": "STRING", "optional": false },
        { "name": "relation_unique_id", "type": "STRING", "optional": false, "index":true, "unique":false },
        { "name": "relation_properties", "type": "STRING", "optional": true }
        ],
      "constraints": [["entity", "entity"]]
    }
  ]
}

复现步骤：
1. 向以上schema图离线写入1.5亿顶点3亿关系边
离线导入过程报bad_alloc。
另外将边属性relation_unique_id改为无索引，数据可以被正常导入。
也希望关系边属性有唯一索引的场景下，支持离线导入

**Comment by ljcui** [comment]
可以测试下在边的json schema里面加上 `"detach_property": true` 配置项，这个会优化加索引的速度和内存消耗，类似下面
```
{
	"label": "relation",
	"type": "EDGE",
	"detach_property": true,
	"properties": [{
			"name": "relation_type",
			"type": "STRING",
			"optional": false
		},
		{
			"name": "relation_unique_id",
			"type": "STRING",
			"optional": false,
			"index": true,
			"unique": false
		},
		{
			"name": "relation_properties",
			"type": "STRING",
			"optional": true
		}
	],
	"constraints": [
		["entity", "entity"]
	]
}
```

**Comment by spasserby** [comment]
PR: #430
