### ISSUE TITLE
lgraph_monitor运行报错

### ISSUE THREAD

**Issue by huzhihao199657** [TuGraph-family/tugraph-db#407]
Docker镜像：tugraph/tugraph-runtime-centos7:4.0.1
报错信息：
terminate called after throwing an instance of 'lgraph:RpcStatusException'
  what():rpc exception:Server returned error:Access denied: Bad user/password.
Aborted(core dumped)

**Comment by huzhihao199657** [comment]
lgraph_monitor --server_host 127.0.0.1:9090 -u admin -p 73@TuGraph
[RpcClient] RpcClient succeeded
terminate called after throwing an instance of 'nlohmann::detail::type_error'
  what():  [json.exception.type_error.305] cannot use operator[] with a string argument with array
Aborted (core dumped)

**Comment by FenJian** [comment]
我也遇到了同样的错，请问怎么解决的？
