### ISSUE TITLE
TuGraph Docker单机版，如何获取每个Cypher请求的耗时

### ISSUE THREAD

**Issue by huzhihao1** [TuGraph-family/tugraph-db#409]
**Is your feature request related to a problem? Please describe.**

A clear and concise description of the problem.

**Describe the solution you'd like**

A clear and concise description of what you want to happen and any alternative solutions or features you've considered.

**Comment by qishipengqsp** [comment]
TuGraph的cli可以看到时间：
https://tugraph-db.readthedocs.io/zh-cn/latest/5.developer-manual/4.client-tools/5.tugraph-cli.html

如果是白屏前端，可以看接口调用的端到端时间

**Comment by huzhihao1** [comment]
> TuGraph的cli可以看到时间： https://tugraph-db.readthedocs.io/zh-cn/latest/5.developer-manual/4.client-tools/5.tugraph-cli.html
> 
> 如果是白屏前端，可以看接口调用的端到端时间
