### ISSUE TITLE
TuGraph是否支持函数式调用

### ISSUE THREAD

**Issue by huzhihao1** [TuGraph-family/tugraph-db#420]
请教下，使用TuGraph restful接口查询耗时长，是否有类似于Neo4j的函数式接口。

环境：Docker镜像
CPU：未限制
磁盘：vda1
点：15w
边：140w
4跳查询返回结果规模：31.5KByte，返回点个数：161070
查询耗时：5+秒
查询SDK：JavaSDK：com.antgroup.tugraph，version：1.4.1

**Comment by jiazhenjiang** [comment]
您说的函数式接口能举个具体的例子么？

**Comment by huzhihao1** [comment]
我记错了Neo4j没有函数式接口，TuGraph除了使用RPC调用，还有没有其他更快的查询方式。当前我们这边有个图数据库，类似于调用UT方法的方式查询，同样的数据规模和查询条件，耗时在几百毫秒。和现有用单机版TuGraph查询耗时5+秒差别很大，而且这个5秒的查询耗时很不正常。

**Comment by ljcui** [comment]
现象知道了，加下钉钉群，拉个小群直接聊。
