### ISSUE TITLE
TuGraph的Rust支持

### ISSUE THREAD

**Issue by xizheyin** [TuGraph-family/tugraph-db#432]
**Is your feature request related to a problem? Please describe.**

你好，我想用Rust来编写TuGraph的客户端，我看Python和C++都有对应的客户端，那么Rust如何来访问Tugraph Server呢？是否有具体的例子，谢谢！

**Describe the solution you'd like**

最好能有一个具体的例子，来展示完全使用Rust代码（无GUI操作）来实现插入脚本，Plugins查询。

**Comment by gtahoo** [comment]
现在TuGraph的客户端统一都走bolt，目前是支持rust的，https://github.com/TuGraph-family/tugraph-db/blob/master/demo/Bolt/rust_example.rs

如果有问题可以在钉钉或微信交流群里找我们，沟通更便捷些
