### ISSUE TITLE
An exception is thrown when executing the Cypher query "MATCH (n0) OPTIONAL MATCH (n0)-->(n1) RETURN *"

### ISSUE THREAD

**Issue by abc123000111** [TuGraph-family/tugraph-db#44]
**Describe the bug**
When I used the Java client to execute the following Cypher query:
```
MATCH (n0) OPTIONAL MATCH (n0)-->(n1) RETURN *
```
An exception occurred:
```
com.alipay.tugraph.TuGraphRpcException: CypherException: Function not implemented yet: AddClause at :211
```

**Expected behavior**
No error occurs because this Cypher query is syntactically correct and valid and the doc says that "OPTIONAL MATCH is supported" .

**Environment:**
 - OS: MacOS 10.15.7
 - Version: TuGraph 3.3.0 docker, Java client

**Comment by spasserby** [comment]
tugraph currently does not support this Cypher query, you can use:
MATCH (n0) WITH n0 OPTIONAL MATCH (n0)-->(n1) RETURN *

**Comment by qishipengqsp** [comment]
The issue is closed due to inactivity. Please feel free to create a new one if you have more questions. And please star this repo if you find it useful! Thanks!

此issue由于长期不活跃被关闭。如有任何问题，可另开 issue 并提供更多信息。如果这个项目帮助到你，可以在仓库右上角 star 一下，感谢你的支持!
