### ISSUE TITLE
i need to change vertex label

### ISSUE THREAD

**Issue by zhuyuemings** [TuGraph-family/tugraph-db#480]
I need to change vertex label, but it is returned:
```
CypherException: Function not implemented yet: visitOC_RemoveItem at :415
```

It is supported in neo4j:
```
MATCH (n) where id(n)=10 set n:scene remove n:app return n
```

**Comment by zhangwh807** [comment]
Currently, the DB is designed with a strong schema type, which currently does not support rapid addition or deletion of fields, nor does it support the above Cypher syntax. This has been planned for this year, and such functionality will be supported in the future.
