### ISSUE TITLE
按快速上手使用docker运行后，无法在7001端口或是8000端口打开browser

### ISSUE THREAD

**Issue by SYguanxin** [TuGraph-family/tugraph-db#499]
**环境:**
- OS: windows 11
- CPU: AMD Ryzen 7 6800H
- TuGraph-DB Version 4.2.0

**Describe the bug**

但是无法在7001端口或是8000端口打开browser，但是7070端口可以打开旧版web

**How to reproduce and expected behavior**

按快速上手，想用docker尝试打开tugraph-db，我的流程如下
* 'docker pull tugraph/tugraph-runtime-centos7:4.2.0'
* 'docker run -it -d -p 7001:7001 -p 7070:7070 -p 7687:7687 -p 8000:8000 -p 8888:8888 -p 8889:8889 -p 9090:9090 -v /root/tugraph/data:/var/lib/lgraph/data  -v /root/tugraph/log:/var/log/lgraph_log --name tugraph_demo tugraph/tugraph-runtime-centos7:4.2.0 /bin/bash'
* ‘docker exec tugraph_demo bash /setup.sh’

**Comment by zhangwh807** [comment]
你好，正常排查逻辑应该是
1.清理浏览器缓存
2.确定7001或者8000端口没有做限制
3.用ps -ef | grep browser命令查看browser进程是否正常
在windows上部署tugraph，是先在windows上安装了linux虚拟机吗？还是直接安装的windows的docker进行部署呢？
欢迎加入微信社区群，更有助于我们细致排查

**Comment by SYguanxin** [comment]
> 你好，正常排查逻辑应该是 1.清理浏览器缓存 2.确定7001或者8000端口没有做限制 3.用ps -ef | grep browser命令查看browser进程是否正常 在windows上部署tugraph，是先在windows上安装了linux虚拟机吗？还是直接安装的windows的docker进行部署呢？ 欢迎加入微信社区群，更有助于我们细致排查

**感谢回复**
> 在windows上部署tugraph，是先在windows上安装了linux虚拟机吗？还是直接安装的windows的docker进行部署呢？  

是直接安装windows的docker进行部署的

> 2.确定7001或者8000端口没有做限制  

我昨天使用本地browser运行时可以正常打开和操作，所以7001和8000应该没有限制

> 3.用ps -ef | grep browser命令查看browser进程是否正常  

返回如下：
```
root      1043     1  1 05:21 ?        00:00:00 /usr/local/share/lgraph/tugraph-db-browser/client/node_modules/@esbuild/linux-x64/bin/esbuild --service=0.17.19 --ping
root      1114  1102  0 05:22 pts/1    00:00:00 grep browser
```
> 欢迎加入微信社区群，更有助于我们细致排查

已经加入，是不是叫`TuGraph社区群`，昨天在群里问，但是没有得到回答

**Comment by Myrrolinz** [comment]
您好，请问您解决这个问题了吗？我也仍然卡在这一步

**Comment by jiandanfeng** [comment]
我也卡在这一步了，有解决方案了吗

**Comment by SYguanxin** [comment]
> 我也卡在这一步了，有解决方案了吗

grep browser找到进程kill
然后重新pnpm run dev
