### ISSUE TITLE
无法通过端口8000打开tugraph-db-browser，但能通过7070打开

### ISSUE THREAD

**Issue by Myrrolinz** [TuGraph-family/tugraph-db#525]
**Environment:**
- OS: [Debian GNU/Linux 12 (bookworm)]
- CPU: [AMD Ryzen 9 5950X]
- TuGraph-DB Version [latest]

**Describe the bug**

无法通过端口8000打开tugraph-db-browser，但能通过7070打开

**How to reproduce and expected behavior**

根据`https://tugraph-db.readthedocs.io/zh-cn/latest/3.quick-start/1.preparation.html`此页面步骤进行

**Comment by zhangwh807** [comment]
进入容器，ps -ef 看下，如果node进程没有起来，你先把ps -ef｜grep browser到的那个进程kill了，然后cd /usr/local/share/lgraph/tugraph-db-browser/ 执行pnpm run dev，手动拉起一下试试
