### ISSUE TITLE
通过docker启动服务时，当执行容器内的setup.sh报错，导致tugraph-db-browser启动失败

### ISSUE THREAD

**Issue by jiandanfeng** [TuGraph-family/tugraph-db#531]
**Environment:**
- OS: centos7
- docker image：tugraph/tugraph-runtime-centos7:4.3.0

通过官网的快速启动，执行到setup.sh时，发生了如下错误 Bad user/password

![image](https://github.com/TuGraph-family/tugraph-db/assets/24525960/0303ae43-d3c6-4573-9c01-80c276b99d12)

**Comment by zhangwh807** [comment]
这个应该是你之前版本更改了密码，现在重新在这个基础上更新了4.3.0版本，这导致与我们默认的初始密码不匹配出现了这个ERROR。应该不会影响tugraph的使用，这个问题我们会记录解决

**Comment by jiandanfeng** [comment]
试过把docker container删掉，重新运行新的容器，执行到setup.sh还是会发生同样的问题

**Comment by zhangwh807** [comment]
你先忽略这个错误，试一下tugraph功能能否正常使用

**Comment by zhangwh807** [comment]
你先忽略这个错误，试一下tugraph功能能否正常使用

**Comment by jiandanfeng** [comment]
我退回到4.2.0，执行setup.sh browser可以正常启动，当browser启动成功后，根据模板来创建图项目时，会报这个错误
![image](https://github.com/TuGraph-family/tugraph-db/assets/24525960/4ab2e7b4-7fa9-435b-a9dc-755958255f5b)

**Comment by zhangwh807** [comment]
是的，会有这个弹窗报错，但是已经根据模版成功创建了图项目，不影响接下来使用。弹窗报错我们会继续跟踪
