### ISSUE TITLE
no viable alternative at input ' `NEXT`'"

### ISSUE THREAD

**Issue by lizhongxiang12138** [TuGraph-family/tugraph-db#532]
**Environment:**
docker  tugraph 版本：4.3.0

执行查询
MATCH (t:Travel_Travel) WHERE t.id = "虎跳峡高路徒步+玉龙雪山秘境丨环线2日游"  RETURN t `NEXT` MATCH (s:Travel_Schedule) WHERE s.Travel_Schedule__Travel_Travel = t RETURN s.day, s.Travel_Schedule__destination__Travel_Destination, s.Travel_Schedule__play__Travel_Destination, s.Travel_Schedule__hotel__Travel_Hotel, s.eat 

报错：
error_message: "[ParserException] ParserException: line 1:70 no viable alternative at input ' `NEXT`'"

**Comment by ljcui** [comment]
NEXT 不是cypher里面的语法
