### ISSUE TITLE
聚合操作都没有利用上索引

### ISSUE THREAD

**Issue by cmwl** [TuGraph-family/tugraph-db#540]
- 测试环境：debian 11, x86_64, docker单机, 8C32G

- 数据建模：单类型节点，1亿个节点

`[
    {
      "label": "Task",
      "type": "VERTEX",
      "properties": [
        {
          "name": "task_id",
          "type": "INT32",
          "optional": false,
          "unique": true,
          "index": true
        },
        {
          "name": "task_name",
          "type": "STRING",
          "optional": false,
          "unique": true,
          "index": true
        },
        {
          "name": "task_time",
          "type": "INT64",
          "optional": false,
          "unique": false,
          "index": true
        }
      ],
      "primary": "task_id"
    }
  ]`

- 查询语句：match (t:Task) return max(t.task_id)

- task_id有索引执行时间：50秒

- task_id无索引执行时间：50秒

- 其它聚合操作函数也都未利用上索引

**Comment by ljcui** [comment]
索引优化正在完善
