### ISSUE TITLE
cypher查询order by问题

### ISSUE THREAD

**Issue by jameFly** [TuGraph-family/tugraph-db#553]
order by后跟的label属性必须要在return中存在，否则报错属性不存在，感觉不太合理
执行成功：MATCH (n:person) RETURN n.age ORDER BY n.age 
报错：MATCH (n:person) RETURN nORDER BY n.name

**Comment by zhangwh807** [comment]
可以先类似这样使用
MATCH (n:person) RETURN n,n.name ORDER BY n.name
