### ISSUE TITLE
能不能改一下文档。

### ISSUE THREAD

**Issue by DoiiarX** [TuGraph-family/tugraph-db#569]
能不能改一下文档。

https://github.com/TuGraph-family/tugraph-db/blob/master/docs/zh-CN/source/3.quick-start/1.preparation.md

这里面步骤很清楚，结果谷歌搜索上面是这个莫名其妙的文档步骤都不齐全还拿来当介绍。这个服务又要暴露端口又要初始化，文档里面根本没说。直接运行根本没反应。

https://tugraph-db.readthedocs.io/zh-cn/latest/5.installation%26running/3.docker-deployment.html

**Comment by zhangwh807** [comment]
感谢您关注TuGraph，我们会继续完善文档，在docker  deployment章节加上相关步骤。
