### ISSUE TITLE
Error opening config file lgraph_standalone.json

### ISSUE THREAD

**Issue by jjwwno** [TuGraph-family/tugraph-db#572]
ubuntu环境下，通过本地包部署的方式安装tugraph，在启动时报错Error opening config file lgraph_standalone.json，这里是以root账户登录的。

**Comment by zhangwh807** [comment]
使用lgraph.json配置文件
例如：/usr/local/bin/lgraph_server -d run -c /usr/local/etc/lgraph.json --log_dir "/xxx/xxx"
