### ISSUE TITLE
能否有一个统一的接口前缀？

### ISSUE THREAD

**Issue by zhang-jinqi** [TuGraph-family/tugraph-db#573]
在部署tugraph的过程中，发现tugraph的web请求路径并没有一个统一的前缀，这样不方便将服务通过nginx代理出来，请问有什么解决方式或者后续能支持统一的请求前缀吗？

**Comment by qishipengqsp** [comment]
当前tugraph-db有2套http的接口，都是rest风格的，相同的功能具有相同的prefix
- 第一套接口的prefix见：https://github.com/TuGraph-family/tugraph-db/blob/master/src/restful/server/rest_server.cpp#L3095。这套接口是tugraph-web调用的接口，后续将被替换掉不建议使用
- 第二套接口的prefix见：https://github.com/TuGraph-family/tugraph-db/blob/master/src/http/http_server.cpp#L151。这套接口是tugraph-db-browser调用的接口，后续将继续维护替代第一套接口。
