### ISSUE TITLE
请更新Mac M1芯片的镜像

### ISSUE THREAD

**Issue by jisumanbu** [TuGraph-family/tugraph-db#579]
arm64/v8架构的镜像还停留在4.1.0，能push最新版本么？

<img width="1163" alt="image" src="https://github.com/TuGraph-family/tugraph-db/assets/27117041/11ec235c-364d-46f3-8286-e8779157c45e">

**Comment by zhangwh807** [comment]
https://tugraph-web.oss-cn-beijing.aliyuncs.com/tugraph/tugraph-runtime-arm64v8-centos7-4.3.0.taz
这是是4.3.0版本的，可以试用下

**Comment by jisumanbu** [comment]
> https://tugraph-web.oss-cn-beijing.aliyuncs.com/tugraph/tugraph-runtime-arm64v8-centos7-4.3.0.taz 这是是4.3.0版本的，可以试用下

3Q，今天我试下
