### ISSUE TITLE
Browser crate graph using graph template falied.

### ISSUE THREAD

**Issue by gukj-spel** [TuGraph-family/tugraph-db#580]
**Environment:**

- OS: 官方提供的 tugraph-compile-ubuntu18.04 编译镜像。docker 运行在 window 11下。
- CPU: Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz
- TuGraph-DB Version：

> TuGraph v4.3.1, compiled from "master" branch, commit "6ed5b75" (web commit "33bd114").
> CPP compiler version: "GNU" "8.4.0".
> Python version : "3.6.9".

**Describe the bug**
在 ubuntu 镜像中编译好 tugraphdb 后，使用命令行启动 lgraph_server， 监听端口 9091，配置为 standalone 模式。 之后启动 browser，在前端页面使用以下配置创建图项目报错，配置和报错信息如下。
![image](https://github.com/TuGraph-family/tugraph-db/assets/61576591/d8af068c-db0a-4b2c-8eae-5ce7660c2f69)

lgraph_server 中打印如下信息。

> [20240628 09:05:20.638920 0x00007f52191ff700 DEBUG src/server/state_machine.cpp:262] Apply a CYPHER request.
> [20240628 09:05:20.639442 0x00007f52191ff700 DEBUG src/cypher/execution_plan/scheduler.cpp:78] -----CLAUSE TO STRING-----
> [20240628 09:05:20.639526 0x00007f52191ff700 DEBUG src/cypher/execution_plan/scheduler.cpp:80] [
> [
> CALL = {dbms.graph.createGraph("Movie", "基于电影、演员、用户场景的简单示例。", 10)::()}
> ]
> ]
> [20240628 09:05:20.639655 0x00007f52191ff700 DEBUG src/cypher/execution_plan/execution_plan.cpp:1202] Plan parts:
> [20240628 09:05:20.639735 0x00007f52191ff700 DEBUG src/cypher/execution_plan/execution_plan.cpp:1205] Produce Results
> Standalone Call []
>
> [20240628 09:05:20.639838 0x00007f52191ff700 DEBUG src/cypher/execution_plan/scheduler.cpp:124] Plan cache disabled.
> [20240628 09:05:20.639940 0x00007f52191ff700 DEBUG src/cypher/execution_plan/scheduler.cpp:126] ReadOnly:0
> Execution Plan:
> Produce Results
>     Standalone Call []
>
> [20240628 09:05:20.640015 0x00007f52191ff700 DEBUG src/cypher/execution_plan/scheduler.cpp:127] Current Pattern Graph:
> (EMPTY GRAPH)
>
> [20240628 09:05:20.640498 0x00007f52191ff700 DEBUG src/server/state_machine.cpp:370] [Calling CYPHER] elapsed=1.58071517e-3, res=EXCEPTION, query=[CALL dbms.graph.createGraph('Movie',  '基于电影、演员、用户场景的简单示例。', 10)]
> [20240628 09:05:20.643351 0x00007f52185ff700 DEBUG src/server/state_machine.cpp:307] Received a schema request.
> [20240628 09:05:20.643486 0x00007f52185ff700 INFO  src/import/import_online.cpp:401] {"schema":[{"label":"person","primary":"id","properties":[{"name":"id","type":"INT32"},{"name":"name","type":"STRING"},{"name":"born","optional":true,"type":"INT32"},{"name":"poster_image","optional":true,"type":"STRING"}],"type":"VERTEX"},{"label":"genre","primary":"id","properties":[{"name":"id","type":"INT32"},{"name":"name","type":"STRING"}],"type":"VERTEX"},{"label":"keyword","primary":"id","properties":[{"name":"id","type":"INT32"},{"name":"name","type":"STRING"}],"type":"VERTEX"},{"label":"movie","primary":"id","properties":[{"name":"id","type":"INT32"},{"index":true,"name":"title","type":"STRING"},{"name":"tagline","type":"STRING"},{"name":"summary","optional":true,"type":"STRING"},{"name":"poster_image","optional":true,"type":"STRING"},{"name":"duration","type":"INT32"},{"name":"rated","optional":true,"type":"STRING"}],"type":"VERTEX"},{"label":"user","primary":"id","properties":[{"name":"id","type":"INT32"},{"index":true,"name":"login","type":"STRING"}],"type":"VERTEX"},{"label":"acted_in","properties":[{"name":"role","type":"STRING"}],"type":"EDGE"},{"label":"rate","properties":[{"name":"stars","type":"INT8"}],"type":"EDGE"},{"label":"directed","type":"EDGE"},{"label":"is_friend","type":"EDGE"},{"label":"has_genre","type":"EDGE"},{"label":"has_keyword","type":"EDGE"},{"label":"produce","type":"EDGE"},{"label":"write","type":"EDGE"}]}
> [20240628 09:05:20.643560 0x00007f52185ff700 INFO  src/import/import_online.cpp:402] ----------
> [20240628 09:05:20.644535 0x00007f52185ff700 INFO  src/import/import_config_parser.h:733] edge label size: 8
> [20240628 09:05:20.644652 0x00007f52185ff700 INFO  src/import/import_config_parser.h:733] vertex label size: 5
> [20240628 09:05:20.656223 0x00007f521417f700 INFO  src/http/import_manager.cpp:130] /root/tugraph-db/build/output/lgraph_db/upload_files/admin/movie/raw_data/vertex_person.csv file remove failed in 42d8a9ee-5a0e-4a2b-8189-b074a7835c42 task
> [20240628 09:05:20.656366 0x00007f521417f700 INFO  src/http/import_manager.cpp:130] /root/tugraph-db/build/output/lgraph_db/upload_files/admin/movie/raw_data/vertex_genre.csv file remove failed in 42d8a9ee-5a0e-4a2b-8189-b074a7835c42 task
> [20240628 09:05:20.656446 0x00007f521417f700 INFO  src/http/import_manager.cpp:130] /root/tugraph-db/build/output/lgraph_db/upload_files/admin/movie/raw_data/vertex_keyword.csv file remove failed in 42d8a9ee-5a0e-4a2b-8189-b074a7835c42 task
> [20240628 09:05:20.656541 0x00007f521417f700 INFO  src/http/import_manager.cpp:130] /root/tugraph-db/build/output/lgraph_db/upload_files/admin/movie/raw_data/vertex_movie.csv file remove failed in 42d8a9ee-5a0e-4a2b-8189-b074a7835c42 task
> [20240628 09:05:20.656624 0x00007f521417f700 INFO  src/http/import_manager.cpp:130] /root/tugraph-db/build/output/lgraph_db/upload_files/admin/movie/raw_data/vertex_user.csv file remove failed in 42d8a9ee-5a0e-4a2b-8189-b074a7835c42 task
> [20240628 09:05:20.656709 0x00007f521417f700 INFO  src/http/import_manager.cpp:130] /root/tugraph-db/build/output/lgraph_db/upload_files/admin/movie/raw_data/edge_acted_in.csv file remove failed in 42d8a9ee-5a0e-4a2b-8189-b074a7835c42 task
> [20240628 09:05:20.656802 0x00007f521417f700 INFO  src/http/import_manager.cpp:130] /root/tugraph-db/build/output/lgraph_db/upload_files/admin/movie/raw_data/edge_rate.csv file remove failed in 42d8a9ee-5a0e-4a2b-8189-b074a7835c42 task
> [20240628 09:05:20.656891 0x00007f521417f700 INFO  src/http/import_manager.cpp:130] /root/tugraph-db/build/output/lgraph_db/upload_files/admin/movie/raw_data/edge_directed.csv file remove failed in 42d8a9ee-5a0e-4a2b-8189-b074a7835c42 task
> [20240628 09:05:20.656982 0x00007f521417f700 INFO  src/http/import_manager.cpp:130] /root/tugraph-db/build/output/lgraph_db/upload_files/admin/movie/raw_data/edge_is_friend.csv file remove failed in 42d8a9ee-5a0e-4a2b-8189-b074a7835c42 task
> [20240628 09:05:20.657073 0x00007f521417f700 INFO  src/http/import_manager.cpp:130] /root/tugraph-db/build/output/lgraph_db/upload_files/admin/movie/raw_data/edge_has_genre.csv file remove failed in 42d8a9ee-5a0e-4a2b-8189-b074a7835c42 task
> [20240628 09:05:20.657156 0x00007f521417f700 INFO  src/http/import_manager.cpp:130] /root/tugraph-db/build/output/lgraph_db/upload_files/admin/movie/raw_data/edge_has_keyword.csv file remove failed in 42d8a9ee-5a0e-4a2b-8189-b074a7835c42 task
> [20240628 09:05:20.657237 0x00007f521417f700 INFO  src/http/import_manager.cpp:130] /root/tugraph-db/build/output/lgraph_db/upload_files/admin/movie/raw_data/edge_produce.csv file remove failed in 42d8a9ee-5a0e-4a2b-8189-b074a7835c42 task
> [20240628 09:05:20.657321 0x00007f521417f700 INFO  src/http/import_manager.cpp:130] /root/tugraph-db/build/output/lgraph_db/upload_files/admin/movie/raw_data/edge_write.csv file remove failed in 42d8a9ee-5a0e-4a2b-8189-b074a7835c42 task
> **How to reproduce and expected behavior**
>
> A clear and concise description of the steps to reproduce it and your expectation. If applicable, add screenshots to help explain your problem.

追踪了一下日志输出，`/root/tugraph-db/build/output/lgraph_db/upload_files` 这个文件夹并不存在。所以导致删除文件的时候失败

ls 输出
![image](https://github.com/TuGraph-family/tugraph-db/assets/61576591/8d351d11-ba1a-4df4-bb5f-ea813769a75b)

src/http/import_manager.cpp 对应的代码
![image](https://github.com/TuGraph-family/tugraph-db/assets/61576591/d7953ba2-33dd-4bae-8b7c-54002d13991e)

**Comment by zhangwh807** [comment]
这是一个已知的问题。你可以忽略这个报错。然后检查下图项目是否创建成功了（应该已经创建了），这个问题正在修复中。

**Comment by gukj-spel** [comment]
> 这是一个已知的问题。你可以忽略这个报错。然后检查下图项目是否创建成功了（应该已经创建了），这个问题正在修复中。

刚看了一下，确实已经创建了。

**Comment by MSZheng20** [comment]
具体数据的csv 可以去哪里下载？

**Comment by qishipengqsp** [comment]
You can download the demo datasets here: https://github.com/TuGraph-family/tugraph-db-demo
