### ISSUE TITLE
Does TuGraph-db support RHEL series or Rockly series OS

### ISSUE THREAD

**Issue by Hec-gitHub** [TuGraph-family/tugraph-db#584]
Does TuGraph db support RHEL or Rockly series OSs when deploying using source code
For example, when deploying on RHEL 8 environment, which configuration files need to be modified.

**Comment by qishipengqsp** [comment]
You could try [the compile environment setup](https://github.com/TuGraph-family/tugraph-db/blob/master/ci/images/tugraph-compile-centos8-Dockerfile) file on CentOS Series, e.g. CentOS 8 for RHEL 8

**Comment by Hec-gitHub** [comment]
> You could try [the compile environment setup](https://github.com/TuGraph-family/tugraph-db/blob/master/ci/images/tugraph-compile-centos8-Dockerfile) file on CentOS Series, e.g. CentOS 8 for RHEL 8
Thank you very much for your prompt reply.
Due to the installation of TuGraph web dependencies, a version library below node 18 is required.
I will build a centOS 8 environment for deploying TuGraph DB.
