### ISSUE TITLE
"Could NOT find OpenSSL" error occurred while deploying the project using source code compilation

### ISSUE THREAD

**Issue by Hec-gitHub** [TuGraph-family/tugraph-db#586]
Project deployment environment: CentOS Stream 9

According to the error message, the OpenSSL environment of the machine has been checked and installed normally.

> [root@localhost build]# openssl -version

> OpenSSL 3.2.2 4 Jun 2024 (Library: OpenSSL 3.2.2 4 Jun 2024)

Use the find method to find the installation path for OpenSSL as follows:

> /usr/include/openssl

Error Info:
[root@localhost build]# cmake .. -DOURSYSTEM=centos9
-- The C compiler identification is GNU 11.4.1
-- The CXX compiler identification is GNU 11.4.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Community version.
-- Found OpenSSL: /usr/include
Wall is enabled.
MockKV is disabled.
Valgrind is disabled.
SQL import/export is disabled.
Address Sanitizer is disabled.
Python support is enabled.
Data dir sharing is disabled. HA will work in replication mode.
Fulltext index is disabled.
Build procedures.
Build with tests.
CMake Warning at Options.cmake:99 (message):
  Build type not set, falling back to RelWithDebInfo mode.

   To specify build type use:
   -DCMAKE_BUILD_TYPE=<mode> where <mode> is in (Debug, Release, Coverage, RelWithDebInfo).
Call Stack (most recent call first):
  CMakeLists.txt:8 (include)

CMAKE_BUILD_TYPE RelWithDebInfo
-- Performing Test COMPILER_SUPPORTS_CXX17
-- Performing Test COMPILER_SUPPORTS_CXX17 - Success
-- Performing Test COMPILER_SUPPORTS_STATIC_GCC
-- Performing Test COMPILER_SUPPORTS_STATIC_GCC - Success
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find OpenSSL (missing: OpenSSL_ssl_LIBRARY
  OpenSSL_crypto_LIBRARY)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindOpenSSL.cmake:22 (find_package_handle_standard_args)
  CMakeLists.txt:43 (find_package)

-- Configuring incomplete, errors occurred!

May I ask what is the reason for the above problem

**Comment by lipanpan03** [comment]
Use the following command to install openssl and recompile TuGraph
```
tar zxf openssl-1.1.1l.tar.gz && cd openssl-1.1.1l && ./config -fPIC --prefix=/usr/local     && make -j && make install     && rm -rf /openssl*
```

**Comment by Hec-gitHub** [comment]
> Use the following command to install openssl and recompile TuGraph
> 
> ```
> tar zxf openssl-1.1.1l.tar.gz && cd openssl-1.1.1l && ./config -fPIC --prefix=/usr/local     && make -j && make install     && rm -rf /openssl*
> ```
Thank you very much for your reply. Following the above method, "Could NOT find OpenSSL" 's error has been resolved.
But a new error has appeared. What is the reason for this error.

> [root@localhost build]# cmake .. -DOURSYSTEM=centos9

-- The C compiler identification is GNU 11.4.1
-- The CXX compiler identification is GNU 11.4.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Community version.
-- Found OpenSSL: /usr/local/include
Wall is enabled.
MockKV is disabled.
Valgrind is disabled.
SQL import/export is disabled.
Address Sanitizer is disabled.
Python support is enabled.
Data dir sharing is disabled. HA will work in replication mode.
Fulltext index is disabled.
Build procedures.
Build with tests.
CMake Warning at Options.cmake:99 (message):
  Build type not set, falling back to RelWithDebInfo mode.

   To specify build type use:
   -DCMAKE_BUILD_TYPE=<mode> where <mode> is in (Debug, Release, Coverage, RelWithDebInfo).
Call Stack (most recent call first):
  CMakeLists.txt:8 (include)


CMAKE_BUILD_TYPE RelWithDebInfo
-- Performing Test COMPILER_SUPPORTS_CXX17
-- Performing Test COMPILER_SUPPORTS_CXX17 - Success
-- Performing Test COMPILER_SUPPORTS_STATIC_GCC
-- Performing Test COMPILER_SUPPORTS_STATIC_GCC - Success
-- Found OpenSSL: /usr/local/include
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Boost (missing: Boost_INCLUDE_DIR log system filesystem)
  (Required is at least version "1.68")
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake/Modules/FindBoost.cmake:2377 (find_package_handle_standard_args)
  CMakeLists.txt:46 (find_package)


-- Configuring incomplete, errors occurred

**Comment by lipanpan03** [comment]
You can refer to our [dockerfile](https://github.com/TuGraph-family/tugraph-db/blob/master/ci/images/tugraph-compile-centos8-Dockerfile). Compiling TuGraph requires many dependencies, which need to be installed in advance. It seems that boost is currently missing.

**Comment by Hec-gitHub** [comment]
> You can refer to our [dockerfile](https://github.com/TuGraph-family/tugraph-db/blob/master/ci/images/tugraph-compile-centos8-Dockerfile). Compiling TuGraph requires many dependencies, which need to be installed in advance. It seems that boost is currently missing.

I seem to understand. Thank you very much for your answer
