### ISSUE TITLE
启动后跳过Bolt:port 7687了，待解决

### ISSUE THREAD

**Issue by Viserion-nlper** [TuGraph-family/tugraph-db#598]
![image](https://github.com/user-attachments/assets/3469957d-6e2f-4212-91f4-94960dc242af)
配置文件已经添加了Bolt:port7687了
为什么启动的时候还是跳过去了
请大佬解决下

**Comment by zhangwh807** [comment]
如社区群沟通，请使用4.3.1版本。4.3.1版本下载链接：https://tugraph-web.oss-cn-beijing.aliyuncs.com/tugraph/tugraph-4.3.1/tugraph-runtime-centos7-4.3.1.tar
