### ISSUE TITLE
请问可以直接可视化阿里的ODPS数据吗

### ISSUE THREAD

**Issue by huifu99** [TuGraph-family/tugraph-db#613]
请问可以直接可视化阿里的ODPS数据吗？

**Comment by zhangwh807** [comment]
目前TuGraph还不支持可视化阿里的ODPS数据。如果需要ODPS的数据导入，可以参考dataX工具https://tugraph-db.readthedocs.io/zh-cn/latest/6.utility-tools/7.tugraph-datax.html
