### ISSUE TITLE
创建本体关系边的时候，Edge Label不能重名？

### ISSUE THREAD

**Issue by zhang-jinqi** [TuGraph-family/tugraph-db#616]
在图谱构建平台中使用本体构建功能时，存在一个问题：如果有多个关系标签（如“人物参加仪式”和“人物参加会议”）在关系展示中都使用了相同的标签（如“参加”），图数据库在尝试存储这些关系时会遇到问题。由于图数据库不允许关系标签重复，导致存储操作失败。
![3c3c5b1dace8bdf98f2554f2752f31b](https://github.com/user-attachments/assets/c013b6b7-315e-43a5-a331-42c5f830f037)
![c35e4fe5ea0ac259414cee10bcd927c](https://github.com/user-attachments/assets/55f77337-099d-4818-823a-dc8fbb0faf5b)
版本是通过docker部署的4.1.0

**Comment by zhangwh807** [comment]
可以试一下最近发布的4.3.2版本：
https://tugraph-web.oss-cn-beijing.aliyuncs.com/tugraph/tugraph-4.3.2/tugraph-runtime-centos7-4.3.2.tar
该版本可以支持
![image](https://github.com/user-attachments/assets/d5080515-3b77-44aa-a6ec-35952df45ac0)
