### ISSUE TITLE
进行数值比较报错，return 10 > 5;

### ISSUE THREAD

**Issue by dragonAndWater** [TuGraph-family/tugraph-db#624]
**Environment:**
镜像：tugraph/tugraph-runtime-centos7:latest

**Describe the bug**

进行数值比较报错，return 10 > 5;

图一是neo4j，图2是tugraph
![ffe1cc49fd67d82fd87ecfb059251b5](https://github.com/user-attachments/assets/58198267-d0df-4a22-81f5-ef184c37ae64)
![8569f8342e1c8d11caa644db4786840](https://github.com/user-attachments/assets/e1bf8ec3-d2bb-4c9b-9f5c-be7eb70523dd)

**Comment by zhjwpku** [comment]
I tried this with binary built from source, got the right result.

![image](https://github.com/user-attachments/assets/4476d07a-bd4b-4459-8538-08551d44c0f2)
