### ISSUE TITLE
需要基于Tugraph实现时间旅行的能力，请问有没有方案上的建议

### ISSUE THREAD

**Issue by w00125533** [TuGraph-family/tugraph-db#625]
1、希望能通过传入历史时间戳，查询到图历史时刻的图状态信息，

**Comment by qishipengqsp** [comment]
是时序图的场景么，展开说说？

**Comment by w00125533** [comment]
> 是时序图的场景么，展开说说？

是的，是时序图的场景，举个例子：

假如图的状态已经演进到t4，我想查看之前的图状态，可以通过传入“t1，t2，t3”时间戳，分别可以获取到t1、t2、t3时刻的图状态。
