### ISSUE TITLE
在高可用模式下，是否能指定follower节点，利用follower节点资源 进行业务分析（或者创建子图），从而将分析的压力负荷分担到多个机器？

### ISSUE THREAD

**Issue by w00125533** [TuGraph-family/tugraph-db#626]
可用模式下，是否能将分析查询的负荷分担到follower节点

**Comment by qishipengqsp** [comment]
基于现在的HA算法，follower不会写数据，只能执行读操作的查询。如果使用我们的ha client，读操作可以load balance。但请注意写操作只会在leader节点执行

**Comment by lipanpan03** [comment]
> 可用模式下，是否能将分析查询的负荷分担到follower节点

除了负载均衡，ha client也可以指定向某个节点发送请求，可以把分析查询制作一个procedure上传到集群中，只在follower上执行该procedure，从而实现分析查询的功能，而不影响leader节点的负载

**Comment by w00125533** [comment]
> > 可用模式下，是否能将分析查询的负荷分担到follower节点
> 
> 除了负载均衡，ha client也可以指定向某个节点发送请求，可以把分析查询制作一个procedure上传到集群中，只在follower上执行该procedure，从而实现分析查询的功能，而不影响leader节点的负载

感谢，解决了我的疑问！
