### ISSUE TITLE
不支持4字节的UTF字符

### ISSUE THREAD

**Issue by michaelmao999** [TuGraph-family/tugraph-db#628]
**Environment:**
- OS: Ubuntu 20.04
- TuGraph-DB Version 4.3.1

**Describe the bug**

当修改点属性时，属性值包含4字节的UTF字符，系统报错

**How to reproduce and expected behavior**

无论是点或者边，属性值包含4字节UTF字符时，系统将报错。比如：𥛚

**Comment by zhangwh807** [comment]
4.3.5版本已经修复此类问题，可以更新最新版本试试

**Comment by zhangwh807** [comment]
4.5.0版本已经修复此类问题，可以更新最新版本试试
