### ISSUE TITLE
4.3.2版本无法添加同名边类型

### ISSUE THREAD

**Issue by Lao-liu666** [TuGraph-family/tugraph-db#633]
服务器版本4.3.2
添加边类型时，无法添加已存在的同名边类型
![微信图片_20240813204434](https://github.com/user-attachments/assets/0ec91cf6-5cce-46d5-ac3d-26f2e5065365)

**Comment by gtahoo** [comment]
点和边类型名称是唯一的，类似于关系型数据库的表名称，你的场景是什么？可以添加微信或钉钉的技术支持群沟通
