### ISSUE TITLE
变长路径且边属性过滤返回错误结果

### ISSUE THREAD

**Issue by zhuangshuqi** [TuGraph-family/tugraph-db#654]
**Environment:**
- OS: centos 7
- TuGraph-DB Version 4.3.1

**Describe the bug**
查询指定边属性的变长路径的返回结果不正确

**How to reproduce and expected behavior**

match (n)-[r:rela*..2]->(m)
where r:role='交易'
return count(n) #返回0，是错误的

**Comment by zhangwh807** [comment]
目前不支持可变长路径查询时用边属性进行过滤
