### ISSUE TITLE
如何本地部署tugraph

### ISSUE THREAD

**Issue by PeachScript** [TuGraph-family/tugraph-db#656]
我在尝试本地部署 TuGraph 时遇到了一些问题。按照官方文档的步骤进行操作，但在执行 `cmake` 命令时出现了错误。以下是我的操作步骤和错误信息：

1. 克隆仓库：`git clone https://github.com/TuGraph-family/tugraph-db.git`
2. 进入目录：`cd tugraph-db`
3. 执行依赖安装脚本：`deps/build_deps.sh`
4. 执行 cmake 命令：`cmake .. -DOURSYSTEM=ubuntu`

错误信息：
```
[错误日志]
```

我的操作系统是 Ubuntu 20.04，使用的 cmake 版本是 3.18.4。

**Comment by zhangwh807** [comment]
具体的错误日志好像没有贴上去，需要贴一下详细的日志打印。另外本地编译需要的依赖比较多，我们这有编译好的安装包可以直接安装：https://tugraph-web.oss-cn-beijing.aliyuncs.com/tugraph/tugraph-4.3.2/tugraph-4.3.2-1.x86_64.deb

**Comment by PeachScript** [comment]
感谢回复，这是贵仓库 Collaborator 在 2024·Inclusion 外滩大会上体验 [Peter Cat](https://petercat.ai/) 给自定义仓库自动创建 issue 能力创建的，现场测试账号是我的 GitHub，请忽略
