### ISSUE TITLE
upsertVertex 非主键字段报错：执行失败 failed to update vertex index, description:[testtest] already exists

### ISSUE THREAD

**Issue by ljhssga** [TuGraph-family/tugraph-db#741]
**Environment:**
- OS: ubuntu 22.04
- CPU: [e.g. Intel Xeon xxxx]
- TuGraph-DB Version 4.5.0

**Describe the bug**
这是我的结构
![image](https://github.com/user-attachments/assets/a7025900-6f37-48ff-be3b-0e105a94818c)
这是我的原始数据
{
  "identity": 53,
  "labels": [
    "entity"
  ],
  "properties": {
    "name": "Bob_Cratchit",
    "id": "Bob_Cratchit",
    "_community_id": "0",
    "description": "--"
  },
  "elementId": "53"
}
这是我的修改语句
CALL db.upsertVertex("entity", [{id: "Bob_Cratchit", name: "Bob_Cratchit", description: "Bob_Cratchit, clerk_to_Ebenezer_Scrooge", _document_id: "0", _chunk_id: "0", _community_id: "0"}])
执行后报错
![image](https://github.com/user-attachments/assets/12520478-7d4e-444d-b802-a96c12410f86)
当我把修改语句的description改为和原始数据一样，他是正确可以执行的

**Comment by Valdanitooooo** [comment]
Same here 😥

**Comment by zhangwh807** [comment]
同样是4.5.0版本，我并没有复现成功，方便的话加一下我们的社区群，我们一起看下
https://github.com/TuGraph-family/tugraph-db?tab=readme-ov-file#6-contact
