### ISSUE TITLE
Which newest neo4j version using python sdk can support the tugraph, i can use 4.4.2 but cant run when > 5.0. Maybe I need to modify some configs?

### ISSUE THREAD

**Issue by GluttonousCat** [TuGraph-family/tugraph-db#759]
**Environment:**
- OS: [e.g. Ubuntu 18.04]
- CPU: [e.g. Intel Xeon xxxx]
- TuGraph-DB Version [e.g. 3.3.0]

**Describe the bug**

A clear and concise description of bug.

**How to reproduce and expected behavior**

A clear and concise description of the steps to reproduce it and your expectation. If applicable, add screenshots to help explain your problem.

**Comment by zhangwh807** [comment]
It appears you are using an older version of TuGraph-DB. The current version of TuGraph-DB has been updated to 4.5.0, and we recommend upgrading to this version to benefit from the latest features and optimizations. If you are upgrading from version 3.3.0, please be cautious as this is a major version transition and there are storage compatibility issues. Ensure to pay special attention to the data directory path mounted on the host machine during the update process.

**Comment by GluttonousCat** [comment]
I have successfully run neo4j which version is 5.24.0 in my env ,  thanks your guidance.
