### ISSUE TITLE
docker镜像tugraph/tugraph-db-centos7里没有lgraph_cypher命令

### ISSUE THREAD

**Issue by seijiang** [TuGraph-family/tugraph-db#76]
我在tugraph browser里进行cypher查询(数据大小十几个g)速度过慢,且出现out of memory问题,于是我想用shell运行cypher查询,但是tugraph/tugraph-db-centos7里没有lgraph_cypher命令

**Comment by knightast** [comment]
It depends on you cypher statement. If the statement returns several gigabytes result, it's recommended to write it to file; if the statement is very complex and access several gigabytes data, you may want to use c++ procedure to accelerate.

**Comment by qishipengqsp** [comment]
此Issue已保持9个月不活跃状态，先关闭，如有问题可以再次开启。
