### ISSUE TITLE
Bad Request when return edge

### ISSUE THREAD

**Issue by czpmango** [TuGraph-family/tugraph-db#77]
**Describe the bug**
Unable to return edge results when pattern is in the form of `()-[e*1]-()` or `()-[e*1..]-()`

**To Reproduce**
```
match p=(v)-[e*1]->(n) return e
match p=(v)-[e*1..]->(n) return e
```

**Expected behavior**
Returns a list of edges matching the constraints of pattern.

**Screenshots**
![image](https://user-images.githubusercontent.com/26356194/194811736-d2d3c66b-0f51-4439-85e7-590ebcae3d43.png)

**Environment:**
 - OS: [e.g. Ubuntu 18.04]
 - CPU: [e.g. Intel(R) Xeon(R) Platinum 8352Y CPU @ 2.20GHz]

**Comment by qishipengqsp** [comment]
Have you tried a space after the edge variable? Like,
`match p=(v)-[e *1]->(n) return e`
