### ISSUE TITLE
ldbc snb test on tugraphdb

### ISSUE THREAD

**Issue by guzhongyan** [TuGraph-family/tugraph-db#86]
The blog says tugraphdb performance is excellent: https://www.tugraph.org/blog?id=0
I'd like to run the similar test with ldbc snb datasets on tugraphdb, Are there any docs guiding and test driver available now?

**Comment by knightast** [comment]
There are attachments in ldbc website: https://ldbcouncil.org/benchmarks/snb/

We will write step by step guide in the future.

**Comment by qishipengqsp** [comment]
@guzhongyan  https://github.com/TuGraph-family/tugraph-snb-interactive

You can refer to this repo for the reproduction.
