### ISSUE TITLE
TuGraph支持分布式吗, 是否可以水平扩展

### ISSUE THREAD

**Issue by Xavier1994** [TuGraph-family/tugraph-db#9]
看文档好像没有看到分布式部署方面的部分(ha貌似也只是高可用性方面的), 想请较一下TuGraph当前是否支持分布式水平扩展

**Comment by hjk41** [comment]
No. Sharding is not supported in the open-source version of TuGraph. The commercial version, which will be publicly available at Q4 of 2022, does support sharding.

**Comment by whitewum** [comment]
How to shard the graph? Edge cut or vertex cut?

**Comment by GoGoMonkey123** [comment]
请问这个sharding大概什么时候上线？还有这个sharding上线后会不会出现一些功能性上的妥协？比如说事务还会支持吗？

**Comment by qishipengqsp** [comment]
关于商业版的问题，请通过`https://www.tugraph.org/`上的联系方式联系我们的售前同事。

About the commercial version, please contact our SA colleagues via `https://www.tugraph.org/`

**Comment by qishipengqsp** [comment]
The issue is closed due to inactivity. Please feel free to create a new one if you have more questions. And please star this repo if you find it useful! Thanks!
此issue由于长期不活跃被关闭。如有任何问题，可另开 issue 并提供更多信息。如果这个项目帮助到你，可以在仓库右上角 star 一下，感谢你的支持!
