### ISSUE TITLE
docker挂载数据目录/VAR/LIB/LGRAPH/DATA以后，重启一个容器实例使用相同数据目录，原数据丢失

### ISSUE THREAD

**Issue by allensky708** [TuGraph-family/tugraph-db#97]
将/VAR/LIB/LGRAPH/DATA数据目录挂载到宿主机目录，更新环境和配置，重启一个容器实例使用原来的数据目录，但是原来的数据都没有了，使用的事3.3.1的版本，目前的docker image是否支持不同实例的数据迁移

**Comment by knightast** [comment]
DB数据是和机器无关的，该DB数据在原容器能看到起来么？在宿主机能看到么？

**Comment by qishipengqsp** [comment]
此Issue已保持8个月不活跃状态，先关闭，如有问题可以再次开启。
